// src/components/AiChat.tsx
'use client';

import { useI18n } from '@/i18n';
import {
  API_KEY_STORAGE_KEY,
  API_URL,
  HEALTH_URL,
  HISTORY_LIMIT,
  RATE_LIMIT,
  SAVE_DEBOUNCE_MS,
  SESSION_KEY,
  STORAGE_KEY,
  STORAGE_VERSION,
  STORAGE_VERSION_KEY,
  WIDTH_KEY,
} from '@/models/AiChat';
import { sleep } from '@/shared/utils/async';
import { getErrorMessage } from '@/shared/utils/errors';
import { generateId } from '@/shared/utils/identifiers';
import { clamp } from '@/shared/utils/numbers';
import { getStorageItem, setStorageItem } from '@/shared/utils/storage';
import type { ChatMessage, ChatRuntime, ChatState, ChatStateUpdate, StreamChunk } from '@/types/chat';
import { ApiState } from '@/types/chat';
import type { AiChatProps, CodeBlockProps, TextContentProps } from '@/types/components';
import type { FormEvent, PointerEvent as ReactPointerEvent } from 'react';
import { Fragment, useEffect, useRef, useState } from 'react';
import AiChatTrashIcon from './AiChatTrashIcon';

const MIN_WIDTH = 480;
const MAX_WIDTH = 1000;

function persistMessages(messages: ChatMessage[]) {
  setStorageItem(STORAGE_VERSION_KEY, String(STORAGE_VERSION));
  setStorageItem(
    STORAGE_KEY,
    messages.length ? JSON.stringify({ version: STORAGE_VERSION, messages: messages.slice(-HISTORY_LIMIT) }) : null
  );
}

function InlineMessage({ text }: TextContentProps) {
  return text.split(/(`[^`\n]+`)/g).map((part, index) =>
    part.startsWith('`') && part.endsWith('`') ? (
      <code key={index} className="inline-code">
        {part.slice(1, -1)}
      </code>
    ) : (
      <Fragment key={index}>
        {part.split(/\r?\n/).map((line, lineIndex) => (
          <Fragment key={lineIndex}>
            {lineIndex > 0 && <br />}
            {line}
          </Fragment>
        ))}
      </Fragment>
    )
  );
}

function CodeBlock({ code, language }: CodeBlockProps) {
  const { t } = useI18n();
  const [copied, setCopied] = useState(false);
  useEffect(() => {
    if (!copied) return;
    const timer = setTimeout(() => setCopied(false), 1200);
    return () => clearTimeout(timer);
  }, [copied]);
  const copy = async () => {
    try {
      if (!navigator.clipboard?.writeText) throw new Error('Clipboard unavailable');
      await navigator.clipboard.writeText(code);
      setCopied(true);
    } catch {
      const input = document.createElement('textarea');
      input.value = code;
      input.style.position = 'fixed';
      input.style.opacity = '0';
      document.body.appendChild(input);
      input.select();
      try {
        if (document.execCommand('copy')) setCopied(true);
      } finally {
        input.remove();
      }
    }
  };
  return (
    <div className="code-group">
      <div className="code-toolbar-outside">
        <span className={`code-lang${language ? '' : ' no-lang'}`}>{language || t('aiChat.codeLabel')}</span>
        <button
          type="button"
          className={`copy-btn${copied ? ' copied' : ''}`}
          disabled={copied}
          aria-label={t('aiChat.copyCodeAria')}
          onClick={copy}
        >
          {t(copied ? 'aiChat.copyCodeDone' : 'aiChat.copyCode')}
        </button>
      </div>
      <pre className="code-block">
        <code>{code}</code>
      </pre>
    </div>
  );
}

function MessageContent({ text }: TextContentProps) {
  const parts = [];
  const pattern = /```([^\n`]*)?\r?\n([\s\S]*?)```/g;
  let match,
    offset = 0;
  while ((match = pattern.exec(text))) {
    if (match.index > offset) parts.push(<InlineMessage key={`text-${offset}`} text={text.slice(offset, match.index)} />);
    parts.push(<CodeBlock key={`code-${match.index}`} language={(match[1] || '').trim()} code={match[2]} />);
    offset = pattern.lastIndex;
  }
  if (offset < text.length) parts.push(<InlineMessage key={`text-${offset}`} text={text.slice(offset)} />);
  return <div className="messageHtml">{parts}</div>;
}

export default function AiChat({ visible = false, title = '', placeholder = '', instruction = '', onClose }: AiChatProps) {
  const { t, locale } = useI18n();
  const [state, setState] = useState<ChatState>({
    messages: [],
    text: '',
    apiKey: '',
    apiKeyDraft: '',
    apiKeyError: '',
    showApiKeyModal: false,
    showApiKeyValue: false,
    aiTyping: false,
    isCancelling: false,
    apiState: ApiState.IDLE,
    currentAiMessageId: null,
    panelWidth: 650,
    rateLimitMessage: '',
    generalError: '',
    showSuggestions: true,
    ready: false,
  });
  const latest = useRef(state);
  const callbacks = useRef({ t, onClose });
  callbacks.current = { t, onClose };
  const runtime = useRef<ChatRuntime>({
    worker: null,
    timers: new Map(),
    sessionId: '',
    requests: [],
    healthController: null,
    requestToken: 0,
    resize: null,
    alive: false,
  });
  const conversation = useRef<HTMLDivElement | null>(null),
    textInput = useRef<HTMLInputElement | null>(null),
    apiKeyInput = useRef<HTMLInputElement | null>(null);
  const patch = (update: ChatStateUpdate) => {
    const values = typeof update === 'function' ? update(latest.current) : update;
    latest.current = { ...latest.current, ...values };
    if (runtime.current.alive) setState(latest.current);
  };
  const hasApiKey = !!state.apiKey.trim();
  const showApiKeyGate = !hasApiKey || state.showApiKeyModal;
  const isBusy = state.aiTyping || state.isCancelling || state.apiState === ApiState.CHECKING || state.apiState === ApiState.WAKING;
  const inputDisabled = isBusy || showApiKeyGate;
  const focusPrimary = () =>
    requestAnimationFrame(() => {
      if (!runtime.current.alive) return;
      const locked = !latest.current.apiKey.trim() || latest.current.showApiKeyModal;
      (locked ? apiKeyInput : textInput).current?.focus();
    });
  const updateMessage = (id: string, text: string) =>
    patch((previous) => ({ messages: previous.messages.map((message) => (message.id === id ? { ...message, text } : message)) }));
  const clearAnimation = (id: string) => {
    clearInterval(runtime.current.timers.get(id));
    runtime.current.timers.delete(id);
  };
  const finalizeMessage = (id: string, cancelled = false) => {
    clearAnimation(id);
    patch((previous) => ({
      ...(previous.currentAiMessageId === id ? { aiTyping: false, isCancelling: false, currentAiMessageId: null } : {}),
      ...(cancelled ? { messages: previous.messages.filter((message) => message.id !== id) } : {}),
    }));
  };
  const receiveWorkerMessage = (event: MessageEvent<StreamChunk>) => {
    if (!runtime.current.alive) return;
    const { messageId, text, done, error, errorKey, errorDetail, cancelled, streaming } = event.data || {};
    if (!messageId || !latest.current.messages.some((message) => message.id === messageId)) return;
    if (error || errorKey) {
      clearAnimation(messageId);
      updateMessage(messageId, errorKey ? callbacks.current.t(errorKey, { message: errorDetail || '' }).trim() : error || '');
      if (done) finalizeMessage(messageId);
      return;
    }
    if (cancelled) {
      finalizeMessage(messageId, true);
      return;
    }
    if (typeof text === 'string') {
      clearAnimation(messageId);
      if (streaming || !done || text.length <= 50) {
        updateMessage(messageId, text);
        if (done) finalizeMessage(messageId);
      } else {
        let position = 50;
        updateMessage(messageId, text.slice(0, position));
        const timer = setInterval(() => {
          position += 50;
          updateMessage(messageId, text.slice(0, position));
          if (position >= text.length) finalizeMessage(messageId);
        }, 30);
        runtime.current.timers.set(messageId, timer);
      }
    } else if (done) finalizeMessage(messageId);
  };
  const ensureWorker = () => {
    if (!runtime.current.worker) {
      const worker = new Worker(new URL('../workers/chat.worker.js', import.meta.url), { type: 'module' });
      worker.addEventListener('message', receiveWorkerMessage);
      worker.addEventListener('error', (event) => {
        const id = latest.current.currentAiMessageId;
        if (id) {
          updateMessage(id, callbacks.current.t('aiChat.fetchFailed', { message: event.message || '' }));
          finalizeMessage(id);
        }
      });
      runtime.current.worker = worker;
    }
    return runtime.current.worker;
  };

  useEffect(() => {
    runtime.current.alive = true;
    const restored: Partial<ChatState> = { ready: true };
    try {
      restored.apiKey = (getStorageItem(API_KEY_STORAGE_KEY) || '').trim();
      restored.apiKeyDraft = restored.apiKey;
      const width = getStorageItem(WIDTH_KEY);
      if (width && Number.isFinite(Number(width))) restored.panelWidth = clamp(Number(width), MIN_WIDTH, MAX_WIDTH);
      const raw = getStorageItem(STORAGE_KEY);
      if (raw) {
        const parsed = JSON.parse(raw);
        const messages = Array.isArray(parsed) ? parsed : parsed?.messages;
        if (Array.isArray(messages))
          restored.messages = messages
            .filter((message) => message && typeof message === 'object')
            .slice(-HISTORY_LIMIT)
            .map((message, index) => ({
              id: typeof message.id === 'string' ? message.id : generateId(`legacy-${index}`),
              sender: message.sender === 'assistant' ? 'assistant' : 'user',
              text: typeof message.text === 'string' ? message.text : '',
              timestamp: typeof message.timestamp === 'number' ? message.timestamp : Date.now(),
            }));
      }
    } catch {}
    runtime.current.sessionId = getStorageItem(SESSION_KEY) || generateId('session');
    setStorageItem(SESSION_KEY, runtime.current.sessionId);
    patch(restored);
    return () => {
      runtime.current.alive = false;
      runtime.current.requestToken += 1;
      runtime.current.healthController?.abort();
      runtime.current.timers.forEach(clearInterval);
      runtime.current.timers.clear();
      runtime.current.worker?.terminate();
      runtime.current.worker = null;
      if (runtime.current.resize) {
        window.removeEventListener('pointermove', runtime.current.resize.move);
        window.removeEventListener('pointerup', runtime.current.resize.stop);
        window.removeEventListener('pointercancel', runtime.current.resize.stop);
        document.body.style.cursor = runtime.current.resize.previousCursor;
        runtime.current.resize = null;
      }
      persistMessages(latest.current.messages);
    };
  }, []);
  useEffect(() => {
    if (!state.ready) return;
    const timer = setTimeout(() => persistMessages(state.messages), SAVE_DEBOUNCE_MS);
    return () => clearTimeout(timer);
  }, [state.messages, state.ready]);
  useEffect(() => {
    if (!state.ready) return;
    const timer = setTimeout(() => setStorageItem(WIDTH_KEY, String(state.panelWidth)), 120);
    return () => clearTimeout(timer);
  }, [state.panelWidth, state.ready]);
  useEffect(() => {
    if (!state.rateLimitMessage) return;
    const timer = setTimeout(() => patch({ rateLimitMessage: '' }), 4000);
    return () => clearTimeout(timer);
  }, [state.rateLimitMessage]);
  useEffect(() => {
    if (visible) focusPrimary();
    else
      patch({ isCancelling: false, showApiKeyModal: false, showApiKeyValue: false, apiKeyError: '', apiKeyDraft: latest.current.apiKey });
  }, [visible, showApiKeyGate]);
  useEffect(() => {
    if (!visible) return;
    const frame = requestAnimationFrame(() => {
      const element = conversation.current;
      if (element) element.scrollTop = element.scrollHeight;
    });
    return () => cancelAnimationFrame(frame);
  }, [state.messages, visible]);
  useEffect(() => {
    if (state.apiState !== ApiState.ERROR) return;
    const timer = setTimeout(() => patch({ apiState: ApiState.IDLE }), 1500);
    return () => clearTimeout(timer);
  }, [state.apiState]);

  const openApiKeyModal = () => {
    patch({ showApiKeyModal: true, apiKeyDraft: latest.current.apiKey, apiKeyError: '', showApiKeyValue: false });
    focusPrimary();
  };
  const closeApiKeyModal = () => {
    if (!latest.current.apiKey.trim()) return;
    patch({ showApiKeyModal: false, apiKeyDraft: latest.current.apiKey, apiKeyError: '', showApiKeyValue: false });
    focusPrimary();
  };
  const saveApiKey = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    const key = latest.current.apiKeyDraft.trim();
    if (!key) {
      patch({ apiKeyError: t('aiChat.apiKey.missingError') });
      focusPrimary();
      return;
    }
    patch({ apiKey: key, apiKeyDraft: key, apiKeyError: '', generalError: '', showApiKeyModal: false, showApiKeyValue: false });
    setStorageItem(API_KEY_STORAGE_KEY, key);
    focusPrimary();
  };
  const clearApiKey = () => {
    patch({ apiKey: '', apiKeyDraft: '', apiKeyError: '', generalError: '', showApiKeyModal: false, showApiKeyValue: false });
    setStorageItem(API_KEY_STORAGE_KEY, null);
    focusPrimary();
  };
  const cancelResponse = () => {
    const id = latest.current.currentAiMessageId;
    if (!id) return;
    runtime.current.worker?.postMessage({ type: 'cancel', messageId: id });
    finalizeMessage(id, true);
  };
  const resetConversation = () => {
    runtime.current.requestToken += 1;
    runtime.current.healthController?.abort();
    if (latest.current.currentAiMessageId)
      runtime.current.worker?.postMessage({ type: 'cancel', messageId: latest.current.currentAiMessageId });
    runtime.current.timers.forEach(clearInterval);
    runtime.current.timers.clear();
    patch({
      messages: [],
      currentAiMessageId: null,
      aiTyping: false,
      isCancelling: false,
      generalError: '',
      rateLimitMessage: '',
      showSuggestions: true,
      apiState: ApiState.IDLE,
    });
    persistMessages([]);
  };
  const ensureModelAwake = async (token: number) => {
    if (!HEALTH_URL) return;
    const controller = new AbortController();
    runtime.current.healthController = controller;
    const timeout = setTimeout(() => controller.abort(), 35000);
    patch({ apiState: ApiState.CHECKING });
    try {
      const response = await fetch(`${HEALTH_URL}${HEALTH_URL.includes('?') ? '&' : '?'}check=1`, { signal: controller.signal });
      if (!response.ok) throw new Error(`HTTP ${response.status}`);
      const body = await response.json().catch(() => ({}));
      if (runtime.current.requestToken !== token) return;
      if (body.upstream_ok === false) {
        patch({ apiState: ApiState.WAKING });
        await fetch(`${HEALTH_URL}${HEALTH_URL.includes('?') ? '&' : '?'}wake=1`, { signal: controller.signal });
        await sleep(1200);
      }
      if (runtime.current.requestToken === token) patch({ apiState: ApiState.IDLE });
    } finally {
      clearTimeout(timeout);
      if (runtime.current.healthController === controller) runtime.current.healthController = null;
    }
  };
  const sendUserMessage = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    const current = latest.current;
    const query = current.text.trim();
    if (!query || current.aiTyping || current.isCancelling || [ApiState.CHECKING, ApiState.WAKING].includes(current.apiState)) return;
    if (!current.apiKey.trim()) {
      openApiKeyModal();
      patch({ apiKeyError: t('aiChat.apiKey.missingError') });
      return;
    }
    const now = Date.now();
    runtime.current.requests = runtime.current.requests.filter((timestamp) => now - timestamp < RATE_LIMIT.windowMs);
    if (runtime.current.requests.length >= RATE_LIMIT.maxRequests) {
      patch({ rateLimitMessage: t('aiChat.rateLimitExceeded') });
      return;
    }
    runtime.current.requests.push(now);
    const requestToken = ++runtime.current.requestToken;
    // The query is sent separately; history contains the preceding turns once each.
    const history = current.messages
      .filter((message) => message.text.trim())
      .slice(-HISTORY_LIMIT)
      .map((message) => ({ role: message.sender, message: message.text }));
    patch({
      generalError: '',
      messages: [...current.messages, { id: generateId('user'), sender: 'user', text: query, timestamp: now }],
      text: '',
      apiState: ApiState.CHECKING,
    });
    try {
      await ensureModelAwake(requestToken);
      if (runtime.current.requestToken !== requestToken || !runtime.current.alive) return;
      const id = generateId('assistant');
      patch((previous) => ({
        apiState: ApiState.IDLE,
        aiTyping: true,
        isCancelling: false,
        currentAiMessageId: id,
        messages: [...previous.messages, { id, sender: 'assistant', text: '', timestamp: Date.now() }],
      }));
      ensureWorker().postMessage({
        type: 'start',
        messageId: id,
        query,
        apiKey: current.apiKey.trim(),
        history,
        sessionId: runtime.current.sessionId,
        apiUrl: API_URL,
        healthUrl: HEALTH_URL,
      });
    } catch (error) {
      if (runtime.current.requestToken !== requestToken || !runtime.current.alive) return;
      patch({
        apiState: ApiState.ERROR,
        generalError: t('aiChat.connectFailed', { message: getErrorMessage(error) }).trim(),
        aiTyping: false,
        isCancelling: false,
        currentAiMessageId: null,
      });
    }
  };
  const startResize = (event: ReactPointerEvent<HTMLDivElement>) => {
    if (runtime.current.resize) return;
    event.preventDefault();
    const startX = event.clientX,
      startWidth = latest.current.panelWidth;
    const previousCursor = document.body.style.cursor;
    const move = (event: PointerEvent) => patch({ panelWidth: clamp(startWidth + startX - event.clientX, MIN_WIDTH, MAX_WIDTH) });
    const stop = () => {
      window.removeEventListener('pointermove', move);
      window.removeEventListener('pointerup', stop);
      window.removeEventListener('pointercancel', stop);
      document.body.style.cursor = previousCursor;
      runtime.current.resize = null;
      setStorageItem(WIDTH_KEY, String(latest.current.panelWidth));
    };
    runtime.current.resize = { move, stop, previousCursor };
    document.body.style.cursor = 'ew-resize';
    window.addEventListener('pointermove', move);
    window.addEventListener('pointerup', stop);
    window.addEventListener('pointercancel', stop);
  };
  if (!visible) return null;
  return (
    <div
      className="chatOverlay"
      onClick={(event) => {
        if (event.target === event.currentTarget) onClose?.();
      }}
    >
      <div
        id="aiChat"
        className="chatPanel show"
        role="dialog"
        aria-modal="true"
        aria-label={title || t('aiChat.title')}
        style={{ width: state.panelWidth }}
        onClick={(event) => event.stopPropagation()}
        onKeyDown={(event) => {
          if (event.key === 'Escape') {
            event.stopPropagation();
            if (state.showApiKeyModal && hasApiKey) closeApiKeyModal();
            else onClose?.();
          }
        }}
      >
        <div className="resizer" onPointerDown={startResize} />
        <header className="chatHeader">
          <div className="chatHeaderTitle">
            <h1>{title || t('aiChat.title')}</h1>
            <span className={`apiKeyChip${hasApiKey ? ' apiKeyChipReady' : ''}`}>
              {t(hasApiKey ? 'aiChat.apiKey.savedBadge' : 'aiChat.apiKey.requiredBadge')}
            </span>
          </div>
          <div className="headerBtns">
            <button className="apiKeyBtn" type="button" onClick={openApiKeyModal} aria-label={t('aiChat.apiKey.buttonAria')}>
              {t(hasApiKey ? 'aiChat.apiKey.changeShort' : 'aiChat.apiKey.addShort')}
            </button>
            <button className="resetBtn" onClick={resetConversation} aria-label={t('aiChat.resetAria')}>
              <AiChatTrashIcon width="22" height="22" className="trashIcon" />
            </button>
            <button className="closeBtn" onClick={onClose} aria-label={t('aiChat.closeAria')}>
              &times;
            </button>
          </div>
        </header>
        <div className={`chatBody${showApiKeyGate ? ' chatBodyLocked' : ''}`}>
          <div id="conversation" ref={conversation}>
            {[ApiState.CHECKING, ApiState.WAKING].includes(state.apiState) && (
              <div className="healthBanner">
                <span>{t(state.apiState === ApiState.CHECKING ? 'aiChat.checking' : 'aiChat.waking')}</span>
                <span className="dots">
                  <span />
                  <span />
                  <span />
                </span>
              </div>
            )}
            {state.showSuggestions && !state.messages.length && (
              <div className="suggestionPanel">
                <div className="suggestionHeader">
                  <span className="suggestionTitle">{t('aiChat.suggestions.title')}</span>
                  <button
                    className="suggestionClose"
                    type="button"
                    onClick={() => patch({ showSuggestions: false })}
                    aria-label={t('aiChat.suggestions.closeAria')}
                  >
                    &times;
                  </button>
                </div>
                <div className="suggestionGrid">
                  {['whatIsW', 'addTwoNumbers', 'firstProgram'].map((key) => (
                    <button
                      key={key}
                      className="suggestionTile"
                      type="button"
                      onClick={() => {
                        patch({ text: t(`aiChat.suggestions.items.${key}`) });
                        if (!hasApiKey) openApiKeyModal();
                        else focusPrimary();
                      }}
                    >
                      <span className="suggestionText">{t(`aiChat.suggestions.items.${key}`)}</span>
                    </button>
                  ))}
                </div>
              </div>
            )}
            <div className="conversationBox" aria-live="polite" aria-relevant="additions text">
              {state.messages.map((message) => {
                const assistant = message.sender === 'assistant',
                  typing = assistant && state.aiTyping && state.currentAiMessageId === message.id;
                return (
                  <div key={message.id} className={`messageBubble ${assistant ? 'messageAi' : 'messageUser'}`}>
                    <div className="iconWrapper">{assistant ? 'AI' : ''}</div>
                    <div className="messageContent">
                      <div className="messageHeader">
                        <span className="senderName">{t(assistant ? 'aiChat.senderAi' : 'aiChat.senderUser')}</span>
                        <span className={`timestamp${typing ? ' timestampAssistant' : ''}`}>
                          {new Date(message.timestamp).toLocaleTimeString(locale || undefined, { hour: '2-digit', minute: '2-digit' })}
                        </span>
                        {typing && (
                          <button
                            className="cancelBtn"
                            type="button"
                            onClick={cancelResponse}
                            disabled={state.isCancelling}
                            aria-label={t('aiChat.cancel')}
                          >
                            &times;
                          </button>
                        )}
                      </div>
                      <div className={`messageText${assistant ? ' messageTextAssistant' : ''}`}>
                        {typing && !message.text ? (
                          <span className="typing">
                            <span />
                            <span />
                            <span />
                          </span>
                        ) : assistant ? (
                          <MessageContent text={message.text} />
                        ) : (
                          message.text
                        )}
                      </div>
                    </div>
                  </div>
                );
              })}
            </div>
          </div>
          <div className="inputArea">
            <p className="inputInstruction">{instruction || t('aiChat.instruction')}</p>
            {(state.rateLimitMessage || state.generalError) && <p className="inputError">{state.rateLimitMessage || state.generalError}</p>}
            <form onSubmit={sendUserMessage}>
              <input
                ref={textInput}
                value={state.text}
                onChange={(event) => patch({ text: event.target.value })}
                placeholder={placeholder || t('aiChat.placeholder')}
                aria-label={placeholder || t('aiChat.placeholder')}
                type="text"
                disabled={inputDisabled}
                aria-disabled={inputDisabled}
              />
              <button className="execution-btn execution-btn--run" type="submit" disabled={inputDisabled || !state.text.trim()}>
                {t('aiChat.send')}
              </button>
            </form>
          </div>
          {showApiKeyGate && (
            <div
              className="apiKeyGate"
              onClick={(event) => {
                if (event.target === event.currentTarget) closeApiKeyModal();
              }}
            >
              <form className="apiKeyCard" onSubmit={saveApiKey}>
                <p className="apiKeyEyebrow">{t('aiChat.apiKey.eyebrow')}</p>
                <h2>{t(hasApiKey ? 'aiChat.apiKey.editTitle' : 'aiChat.apiKey.title')}</h2>
                <p className="apiKeyDescription">{t(hasApiKey ? 'aiChat.apiKey.editDescription' : 'aiChat.apiKey.description')}</p>
                <label className="apiKeyLabel" htmlFor="ai-chat-api-key">
                  {t('aiChat.apiKey.label')}
                </label>
                <div className="apiKeyField">
                  <input
                    id="ai-chat-api-key"
                    ref={apiKeyInput}
                    value={state.apiKeyDraft}
                    onChange={(event) => patch({ apiKeyDraft: event.target.value })}
                    type={state.showApiKeyValue ? 'text' : 'password'}
                    placeholder={t('aiChat.apiKey.placeholder')}
                    autoComplete="off"
                    spellCheck={false}
                  />
                  <button className="apiKeyToggle" type="button" onClick={() => patch({ showApiKeyValue: !state.showApiKeyValue })}>
                    {t(state.showApiKeyValue ? 'aiChat.apiKey.hide' : 'aiChat.apiKey.show')}
                  </button>
                </div>
                <p className="apiKeyHint">{t('aiChat.apiKey.hint')}</p>
                <div className="apiKeyNotice">
                  <p className="apiKeyNoticeTitle">{t('aiChat.apiKey.noticeTitle')}</p>
                  <ul className="apiKeyNoticeList">
                    {['noticeRateLimits', 'noticeStorage', 'noticeShare'].map((key) => (
                      <li key={key}>{t(`aiChat.apiKey.${key}`)}</li>
                    ))}
                  </ul>
                </div>
                {state.apiKeyError && <p className="apiKeyError">{state.apiKeyError}</p>}
                <div className="apiKeyActions">
                  <button className="execution-btn execution-btn--run apiKeyPrimary" type="submit">
                    {t('aiChat.apiKey.save')}
                  </button>
                  {hasApiKey && (
                    <>
                      <button className="apiKeySecondary" type="button" onClick={closeApiKeyModal}>
                        {t('actions.cancel')}
                      </button>
                      <button className="apiKeySecondary apiKeyDanger" type="button" onClick={clearApiKey}>
                        {t('aiChat.apiKey.clear')}
                      </button>
                    </>
                  )}
                </div>
              </form>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

// src/components/AiChat.vue
<template>
  <div v-if="props.visible" class="chatOverlay" @click.self="startClose">
    <div id="aiChat" class="chatPanel" @click.stop :class="{ show: props.visible }" :style="{ width: panelWidth + 'px' }">
      <div class="resizer" @mousedown="startResize"></div>

      <header class="chatHeader">
        <h1>{{ props.title }}</h1>
        <div class="headerBtns">
          <button class="resetBtn" @click="resetConversation" :aria-label="$t('aiChat.resetAria')">
            <AiChatTrashIcon width="22" height="22" class="trashIcon" />
          </button>
          <button class="closeBtn" @click="startClose" :aria-label="$t('aiChat.closeAria')">&times;</button>
        </div>
      </header>

      <div id="conversation" ref="conversationEl">
        <div v-if="apiState === ApiState.CHECKING || apiState === ApiState.WAKING" class="healthBanner">
          <span v-if="apiState === ApiState.CHECKING">{{ $t('aiChat.checking') }}</span>
          <span v-else>{{ $t('aiChat.waking') }}</span>
          <span class="dots"><span></span><span></span><span></span></span>
        </div>

        <transition-group name="messageEnter" tag="div" class="conversationBox">
          <div
            v-for="msg in messages"
            :key="msg.id"
            class="messageBubble"
            :class="{ messageUser: msg.sender === 'user', messageAi: msg.sender === 'assistant' }"
          >
            <div class="iconWrapper">
              {{ msg.sender === 'assistant' ? '🤖' : '' }}
            </div>
            <div class="messageContent">
            <div class="messageHeader">
              <span class="senderName">{{ msg.sender === 'assistant' ? $t('aiChat.senderAi') : $t('aiChat.senderUser') }}</span>
              <span
                class="timestamp"
                :class="{ timestampAssistant: msg.sender === 'assistant' && aiTyping && msg.id === currentAiMessageId }"
              >
                {{ formatTime(msg.timestamp) }}
              </span>
              <button
                v-if="msg.sender === 'assistant' && aiTyping && msg.id === currentAiMessageId"
                class="cancelBtn"
                type="button"
                @click="cancelResponse"
                :disabled="isCancelling"
                :aria-label="$t('aiChat.cancel')"
              >
                &times;
              </button>
              </div>
              <div class="messageText" :class="{ messageTextAssistant: msg.sender === 'assistant' }">
                <template v-if="msg.sender === 'assistant' && aiTyping && msg.id === currentAiMessageId && !msg.text">
                  <span class="typing"><span></span><span></span><span></span></span>
                </template>
                <template v-else-if="msg.sender === 'assistant'">
                  <div class="messageHtml" v-html="renderMessage(msg.text)" @click="onMessageHtmlClick"></div>
                </template>
                <template v-else>
                  {{ msg.text }}
                </template>
              </div>
            </div>
          </div>
        </transition-group>
      </div>

      <div class="inputArea">
        <p class="inputInstruction">{{ props.instruction }}</p>
        <p v-if="rateLimitMessage" class="inputError">{{ rateLimitMessage }}</p>
        <p v-else-if="generalError" class="inputError">{{ generalError }}</p>
        <form @submit.prevent="sendUserMessage">
          <input ref="textInput" v-model="text" :placeholder="props.placeholder" type="text" :disabled="isBusy" />
          <button class="execution-btn execution-btn--run" type="submit" :disabled="isBusy">{{ $t('aiChat.send') }}</button>
        </form>
      </div>
    </div>
  </div>
</template>

<script setup>
import { computed, nextTick, onBeforeUnmount, onMounted, ref, watch } from 'vue';
import AiChatTrashIcon from '@/components/AiChatTrashIcon.vue';
import {
  ApiState,
  STORAGE_KEY,
  STORAGE_VERSION,
  STORAGE_VERSION_KEY,
  WIDTH_KEY,
  SESSION_KEY,
  HISTORY_LIMIT,
  SAVE_DEBOUNCE_MS,
  RATE_LIMIT,
} from '@/models/AiChat';

const props = defineProps({
  visible: { type: Boolean, default: false },
  title: { type: String, default: 'Asystent AI' },
  placeholder: { type: String, default: 'Napisz wiadomość…' },
  instruction: { type: String, default: 'Opisz operację, aby otrzymać kod maszynowy:' },
});

const emit = defineEmits(['close']);

const messages = ref([]);
const text = ref('');
const aiTyping = ref(false);
const isCancelling = ref(false);
const conversationEl = ref(null);
const textInput = ref(null);
const apiState = ref(ApiState.IDLE);
const currentAiMessageId = ref(null);
const panelWidth = ref(650);
const rateLimitMessage = ref('');
const generalError = ref('');
const requestTimestamps = ref([]);
const sessionId = ref('');

const API_URL = import.meta.env.VITE_API_URL || '';
const HEALTH_URL = API_URL ? API_URL.replace(/\/api\/chat\/?$/, '/health') : '';

const isBusy = computed(
  () => aiTyping.value || isCancelling.value || apiState.value === ApiState.CHECKING || apiState.value === ApiState.WAKING
);

const MIN_WIDTH = 480;
const MAX_WIDTH = 1000;

let worker = null;
let saveTimer = null;
let widthSaveTimer = null;
let rateLimitTimer = null;
let healthToken = 0;
let isResizing = false;
const animationStates = new Map();
const animationPromises = new Map();

const sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms));

function startClose() {
  emit('close');
}

function generateId(prefix = 'msg') {
  if (typeof crypto !== 'undefined' && crypto.randomUUID) {
    return `${prefix}-${crypto.randomUUID()}`;
  }
  return `${prefix}-${Math.random().toString(36).slice(2)}${Date.now()}`;
}

function ensureWorker() {
  if (worker) return worker;
  worker = new Worker(new URL('@/workers/chat.worker.js', import.meta.url), { type: 'module' });
  worker.addEventListener('message', handleWorkerMessage);
  return worker;
}

function findMessage(messageId) {
  return messages.value.find((msg) => msg.id === messageId) || null;
}

const TYPEWRITER_CHARS = 50;
const TYPEWRITER_DELAY_MS = 30;

function stopMessageAnimation(messageId) {
  const state = animationStates.get(messageId);
  if (!state) return;
  state.finish();
}

function stopAllAnimations() {
  const ids = Array.from(animationStates.keys());
  ids.forEach((id) => stopMessageAnimation(id));
}

/**
 * Visual-only typewriter effect for assistant replies. We may replace this with real
 * streaming in the future, at which point chunking/scheduling would move back to the worker.
 */
function playMessageAnimation(message, fullText) {
  stopMessageAnimation(message.id);

  const textValue = fullText || '';
  if (!textValue) {
    message.text = '';
    return Promise.resolve();
  }

  const chunks = [];
  for (let i = 0; i < textValue.length; i += TYPEWRITER_CHARS) {
    chunks.push(textValue.slice(i, i + TYPEWRITER_CHARS));
  }

  return new Promise((resolve) => {
    let index = 0;
    message.text = '';
    let finished = false;
    const state = {
      timer: null,
      finish: () => {
        if (finished) return;
        finished = true;
        if (state.timer !== null) {
          clearInterval(state.timer);
        }
        animationStates.delete(message.id);
        resolve();
      },
    };

    const applyChunk = () => {
      if (finished || index >= chunks.length) {
        state.finish();
        return;
      }
      message.text += chunks[index];
      index += 1;
      if (index >= chunks.length) {
        state.finish();
      }
    };

    animationStates.set(message.id, state);
    applyChunk();

    if (!finished) {
      state.timer = setInterval(() => {
        applyChunk();
        if (finished) {
          clearInterval(state.timer);
        }
      }, TYPEWRITER_DELAY_MS);
    }
  });
}

function scheduleSave() {
  if (saveTimer) clearTimeout(saveTimer);

  saveTimer = setTimeout(() => {
    try {
      if (!messages.value.length) {
        localStorage.removeItem(STORAGE_KEY);
        localStorage.setItem(STORAGE_VERSION_KEY, String(STORAGE_VERSION));
        return;
      }
      const trimmed = messages.value.slice(-HISTORY_LIMIT);
      const payload = { version: STORAGE_VERSION, messages: trimmed };
      localStorage.setItem(STORAGE_VERSION_KEY, String(STORAGE_VERSION));
      localStorage.setItem(STORAGE_KEY, JSON.stringify(payload));
    } catch {}
  }, SAVE_DEBOUNCE_MS);
}

function scheduleWidthPersist() {
  if (widthSaveTimer) clearTimeout(widthSaveTimer);
  widthSaveTimer = setTimeout(() => {
    try {
      localStorage.setItem(WIDTH_KEY, String(panelWidth.value));
    } catch {}
  }, 120);
}

function restorePanelWidth() {
  try {
    const saved = Number(localStorage.getItem(WIDTH_KEY));
    if (!Number.isNaN(saved)) {
      panelWidth.value = Math.min(Math.max(saved, MIN_WIDTH), MAX_WIDTH);
    }
  } catch {
    panelWidth.value = 650;
  }
}

function ensureSession() {
  try {
    let stored = localStorage.getItem(SESSION_KEY);
    if (!stored) {
      stored = generateId('session');
      localStorage.setItem(SESSION_KEY, stored);
    }
    sessionId.value = stored;
  } catch {
    sessionId.value = generateId('session');
  }
}

function loadPersistedMessages() {
  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    if (!raw) return;

    let parsed = JSON.parse(raw);
    if (Array.isArray(parsed)) {
      parsed = { messages: parsed };
    }
    if (!parsed || !Array.isArray(parsed.messages)) return;

    messages.value = parsed.messages.slice(-HISTORY_LIMIT).map((msg, index) => ({
      id: typeof msg.id === 'string' ? msg.id : generateId(`legacy-${index}`),
      sender: msg.sender === 'assistant' ? 'assistant' : 'user',
      text: typeof msg.text === 'string' ? msg.text : '',
      timestamp: typeof msg.timestamp === 'number' ? msg.timestamp : Date.now(),
    }));
  } catch {
    messages.value = [];
  }
}

let rafQueued = false;
function scrollToBottom(behavior = 'auto') {
  const el = conversationEl.value;
  if (!el) return;
  el.scrollTo({ top: el.scrollHeight, behavior });
}

function scheduleScroll(behavior = 'auto') {
  if (rafQueued) return;
  rafQueued = true;

  requestAnimationFrame(() => {
    rafQueued = false;
    nextTick(() => scrollToBottom(behavior));
  });
}

function setRateLimitNotice(message) {
  rateLimitMessage.value = message;
  if (rateLimitTimer) clearTimeout(rateLimitTimer);

  rateLimitTimer = setTimeout(() => {
    rateLimitMessage.value = '';
    rateLimitTimer = null;
  }, 4000);
}

async function ensureModelAwake() {
  if (!HEALTH_URL) return;

  const token = ++healthToken;
  apiState.value = ApiState.CHECKING;

  try {
    const response = await fetch(`${HEALTH_URL}?check=1`);
    const body = await response.json().catch(() => ({}));

    if (token !== healthToken) return;

    if (body && body.upstream_ok === false) {
      apiState.value = ApiState.WAKING;
      await fetch(`${HEALTH_URL}?wake=1`).catch(() => {});

      if (token !== healthToken) return;
      await sleep(1200);
    }
  } catch (err) {
    if (token === healthToken) {
      apiState.value = ApiState.ERROR;
    }
    throw err;
  } finally {
    if (token === healthToken && apiState.value !== ApiState.ERROR) {
      apiState.value = ApiState.IDLE;
    }
  }
}

function buildHistory(excludeId) {
  return messages.value
    .filter((msg) => msg.id !== excludeId && msg.text && msg.text.trim() !== '')
    .slice(-HISTORY_LIMIT)
    .map((msg) => ({
      role: msg.sender === 'assistant' ? 'assistant' : 'user',
      message: msg.text,
    }));
}

function handleWorkerMessage(event) {
  const data = event.data || {};
  const { messageId, text: fullText, done, error, cancelled } = data;
  if (!messageId) return;

  const msg = findMessage(messageId);
  if (!msg) return;

  if (typeof fullText === 'string') {
    scheduleScroll('auto');
    const animation = playMessageAnimation(msg, fullText);
    animationPromises.set(messageId, animation);
    animation.finally(() => {
      animationPromises.delete(messageId);
      scheduleSave();
    });
  }

  if (error) {
    stopMessageAnimation(messageId);
    msg.text = error;
    scheduleSave();
  }

  if (done) {
    const finalize = () => {
      if (messageId === currentAiMessageId.value) {
        aiTyping.value = false;
        isCancelling.value = false;
        currentAiMessageId.value = null;
      }
      if (cancelled) {
        const index = messages.value.findIndex((item) => item.id === messageId);
        if (index !== -1) {
          messages.value.splice(index, 1);
        }
      }
      scheduleSave();
      scheduleScroll('smooth');
    };

    const pending = animationPromises.get(messageId);
    if (pending) {
      pending.finally(finalize);
    } else {
      finalize();
    }
  }
}

async function sendUserMessage() {
  const userQuery = text.value.trim();
  if (!userQuery || isBusy.value) return;

  const now = Date.now();
  requestTimestamps.value = requestTimestamps.value.filter((ts) => now - ts < RATE_LIMIT.windowMs);
  if (requestTimestamps.value.length >= RATE_LIMIT.maxRequests) {
    setRateLimitNotice(RATE_LIMIT.message || 'Przekroczono limit zapytań.');
    return;
  }

  generalError.value = '';
  requestTimestamps.value.push(now);

  const userMessage = {
    id: generateId('user'),
    sender: 'user',
    text: userQuery,
    timestamp: now,
  };
  messages.value.push(userMessage);
  text.value = '';

  scheduleSave();
  scheduleScroll('smooth');

  try {
    await ensureModelAwake();
  } catch (err) {
    const errorMessage = `Nie udało się połączyć z modelem. ${err?.message || ''}`.trim();
    generalError.value = errorMessage;
    aiTyping.value = false;
    isCancelling.value = false;
    setTimeout(() => {
      if (apiState.value === ApiState.ERROR) {
        apiState.value = ApiState.IDLE;
      }
    }, 1500);
    return;
  }

  aiTyping.value = true;
  isCancelling.value = false;
  const assistantMessageId = generateId('assistant');
  const assistantMessage = {
    id: assistantMessageId,
    sender: 'assistant',
    text: '',
    timestamp: Date.now(),
  };
  messages.value.push(assistantMessage);
  currentAiMessageId.value = assistantMessageId;
  scheduleSave();
  scheduleScroll('smooth');

  const history = buildHistory(assistantMessageId);
  ensureWorker().postMessage({
    type: 'start',
    messageId: assistantMessageId,
    query: userQuery,
    history,
    sessionId: sessionId.value,
  });
}

function cancelResponse() {
  if (!currentAiMessageId.value) return;
  isCancelling.value = true;

  stopMessageAnimation(currentAiMessageId.value);
  if (worker) {
    worker.postMessage({ type: 'cancel', messageId: currentAiMessageId.value });
  }

  const idx = messages.value.findIndex((item) => item.id === currentAiMessageId.value);
  if (idx !== -1) {
    messages.value.splice(idx, 1);
  }

  currentAiMessageId.value = null;
  aiTyping.value = false;
  scheduleSave();
  scheduleScroll('auto');
}

function resetConversation() {
  if (currentAiMessageId.value && worker) {
    worker.postMessage({ type: 'cancel', messageId: currentAiMessageId.value });
  }
  currentAiMessageId.value = null;
  aiTyping.value = false;
  isCancelling.value = false;

  stopAllAnimations();

  messages.value = [];
  requestTimestamps.value = [];
  generalError.value = '';
  rateLimitMessage.value = '';

  scheduleSave();
  try {
    localStorage.removeItem(STORAGE_KEY);
  } catch {}
  scheduleScroll('auto');
}

const formatTime = (ts) => new Date(ts).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });

const escapeHtml = (s) =>
  s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;').replace(/'/g, '&#39;');

function renderMessage(textValue) {
  if (!textValue) return '';
  let out = escapeHtml(textValue);

  const blocks = [];
  out = out.replace(/```([^\n`]*)?\r?\n([\s\S]*?)```/g, (_, lang, code) => {
    const id = blocks.length;
    blocks.push({ lang: escapeHtml((lang || '').trim()), code });
    return `%%CODEBLOCK_${id}%%`;
  });

  out = out.replace(/`([^`\n]+)`/g, '<code class="inline-code">$1</code>');
  out = out.replace(/\r?\n/g, '<br>');

  blocks.forEach((block, index) => {
    const langLabel = block.lang ? `<span class="code-lang">${block.lang}</span>` : `<span class="code-lang no-lang">kod</span>`;
    const toolbar = `<div class="code-toolbar-outside">${langLabel}<button type="button" class="copy-btn" aria-label="Skopiuj kod">Kopiuj</button></div>`;
    const group = `<div class="code-group">${toolbar}<pre class="code-block"><code>${block.code}</code></pre></div>`;
    out = out.replace(`%%CODEBLOCK_${index}%%`, group);
  });

  return out;
}

function onMessageHtmlClick(event) {
  const btn = event.target.closest('.copy-btn');
  if (!btn) return;

  const group = btn.closest('.code-group');
  const codeEl = group?.querySelector('pre.code-block > code');
  const codeText = codeEl?.innerText || codeEl?.textContent || '';
  if (!codeText) return;

  const onCopied = () => {
    const original = btn.textContent;
    btn.textContent = 'Skopiowano!';
    btn.disabled = true;
    btn.classList.add('copied');

    setTimeout(() => {
      btn.textContent = original;
      btn.disabled = false;
      btn.classList.remove('copied');
    }, 1200);
  };

  if (navigator.clipboard?.writeText) {
    navigator.clipboard
      .writeText(codeText)
      .then(onCopied)
      .catch(() => fallbackCopy(codeText, onCopied));
  } else {
    fallbackCopy(codeText, onCopied);
  }
}

function fallbackCopy(textValue, done) {
  const ta = document.createElement('textarea');
  ta.value = textValue;
  document.body.appendChild(ta);
  ta.select();
  try {
    document.execCommand('copy');
    done();
  } finally {
    document.body.removeChild(ta);
  }
}

watch(
  () => props.visible,
  (visible) => {
    if (visible) {
      nextTick(() => {
        textInput.value?.focus();
        scheduleScroll('auto');
      });
    } else {
      isCancelling.value = false;
    }
  }
);

watch(
  () => messages.value.length,
  () => nextTick(() => scheduleScroll('auto'))
);

let startX = 0;
let startWidth = 0;

function startResize(e) {
  if (isResizing) return;
  isResizing = true;
  startX = e.clientX;
  startWidth = panelWidth.value;
  window.addEventListener('mousemove', onMouseMove);
  window.addEventListener('mouseup', stopResize);
}

function onMouseMove(e) {
  if (!isResizing) return;
  const delta = startX - e.clientX;
  const nextWidth = Math.min(Math.max(startWidth + delta, MIN_WIDTH), MAX_WIDTH);
  panelWidth.value = nextWidth;
  scheduleWidthPersist();
}

function stopResize() {
  if (!isResizing) return;
  isResizing = false;
  window.removeEventListener('mousemove', onMouseMove);
  window.removeEventListener('mouseup', stopResize);
  scheduleWidthPersist();
}

onMounted(() => {
  ensureWorker();
  restorePanelWidth();
  loadPersistedMessages();
  ensureSession();
  if (props.visible) {
    nextTick(() => {
      textInput.value?.focus();
      scheduleScroll('auto');
    });
  }
});

onBeforeUnmount(() => {
  stopResize();
  stopAllAnimations();
  if (saveTimer) clearTimeout(saveTimer);
  if (widthSaveTimer) clearTimeout(widthSaveTimer);
  if (rateLimitTimer) clearTimeout(rateLimitTimer);
  if (worker) {
    worker.removeEventListener('message', handleWorkerMessage);
    worker.terminate();
    worker = null;
  }
});
</script>

<style scoped>
.inputError {
  margin: 0.3rem 0;
  color: #ef4444;
  font-size: 0.85rem;
}

.messageHtml :deep(.code-group) {
  margin: 0.6rem 0;
}

.messageHtml :deep(.code-toolbar-outside) {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 0.5rem;
  padding: 0 0 0.35rem;
  background: transparent;
}

.messageHtml :deep(.code-lang) {
  font-size: 0.72rem;
  text-transform: uppercase;
  letter-spacing: 0.04em;
  color: #6b7280;
}
.messageHtml :deep(.code-lang.no-lang) {
  opacity: 0.6;
}

.messageHtml :deep(.copy-btn) {
  appearance: none;
  border: 3px solid #003c7d;
  background: var(--panelBackgroundColor, #ffffff);
  color: var(--fontColor, black);
  font-size: 0.8rem;
  padding: 0.25rem 0.6rem;
  border-radius: 6px;
  outline: none;
  cursor: pointer;
}
.messageHtml :deep(.copy-btn:hover) {
  background: #f3f4f6;
}
.messageHtml :deep(.copy-btn.copied) {
  background: #d1fae5;
  border-color: #10b981;
  color: #065f46;
}

.messageHtml :deep(.code-block) {
  font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', monospace;
  background: #0f172a;
  color: #e5e7eb;
  border-radius: 8px;
  padding: 0.8rem 1rem;
  overflow: auto;
  line-height: 1.45;
  border: 1px solid #1f2937;
}

.messageHtml :deep(.inline-code) {
  font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', monospace;
  background: var(--panelBackgroundColor, #ffffff);
  border: 1px solid #e1e4e8;
  padding: 0.15rem 0.35rem;
  border-radius: 4px;
  font-size: 0.95em;
}

.messageText :deep(pre),
.messageText :deep(code),
.messageText :deep(.code-toolbar-outside) {
  margin-top: 0.2rem;
  margin-bottom: 0.2rem;
}

.healthBanner {
  margin: 0.4rem 0 0.6rem;
  padding: 0.5rem 0.75rem;
  border: 1px dashed var(--signal-active, #0ea5e9);
  background: color-mix(in srgb, var(--panelBackgroundColor, #fff) 85%, #0ea5e9);
  border-radius: 8px;
  font-size: 0.9rem;
  display: flex;
  align-items: center;
  gap: 0.5rem;
}
.healthBanner .dots {
  display: inline-flex;
  gap: 0.2rem;
}
.healthBanner .dots span {
  width: 6px;
  height: 6px;
  border-radius: 50%;
  background: #0e7490;
  opacity: 0.3;
  animation: blink 1.4s infinite;
}
.healthBanner .dots span:nth-child(2) {
  animation-delay: 0.2s;
}
.healthBanner .dots span:nth-child(3) {
  animation-delay: 0.4s;
}

@keyframes blink {
  0%,
  80%,
  100% {
    opacity: 0.2;
  }
  40% {
    opacity: 1;
  }
}
</style>
