// src/components/BusLabel.vue
<template>
  <span v-if="showInvisibleRegisters && !mobileView">
    {{ busName }} : {{ formatNumber(busValue) }}
  </span>
  <span v-if="!mobileView">
    {{ busName.toLowerCase() }}
  </span>
</template>

<script>
export default {
  name: 'BusLabel',
  props: {
    busName: { type: String, required: true },
    busValue: { type: Number, required: true },
    showInvisibleRegisters: { type: Boolean, default: false },
    mobileView: { type: Boolean, required: true },
    formatNumber: { type: Function, required: true },
  },
};
</script>

// src/components/BusLabel.tsx
import type { BusLabelProps } from '@/types/components';
export default function BusLabel({ busName, busValue, showInvisibleRegisters = false, mobileView = false, formatNumber }: BusLabelProps) {
  if (mobileView) return null;
  return (
    <>
      {showInvisibleRegisters && (
        <span style={{ marginRight: 5 }}>
          {busName} : {formatNumber(busValue)}
        </span>
      )}
      <span>{busName.toLowerCase()}</span>
    </>
  );
}
