// src/Components/CommandList.tsx
'use client';

import { useI18n } from '@/I18n/Index';
import { collectCommandAliases, normalizeMnemonicToken } from '@/Shared/Utils/CommandMnemonics';
import { cloneJson } from '@/Shared/Utils/Json';
import type { ActionIconProps, CommandListProps } from '@/Types/Components';
import type { RuntimeCommand } from '@/Types/Registry';
import { useEffect, useRef, useState } from 'react';

function ActionIcon({ name }: ActionIconProps) {
  const paths = {
    trash: (
      <>
        <polyline data-editor-command-list="" points="3 6 5 6 21 6" />
        <path data-editor-command-list="" d="M19 6l-1 14a2 2 0 0 1-2 2H8a2 2 0 0 1-2-2L5 6" />
        <path data-editor-command-list="" d="M10 11v6m4-6v6" />
        <path data-editor-command-list="" d="M15 6V4a2 2 0 0 0-2-2h-2a2 2 0 0 0-2 2v2" />
      </>
    ),
    confirm: <polyline data-editor-command-list="" points="20 6 9 17 4 12" />,
    cancel: <path data-editor-command-list="" d="M18 6L6 18M6 6l12 12" />,
    edit: (
      <path
        data-editor-command-list=""
        d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z"
      />
    ),
    add: (
      <>
        <path data-editor-command-list="" d="M12 16V8m4 4H8" />
        <circle data-editor-command-list="" cx="12" cy="12" r="9" />
      </>
    ),
    load: (
      <path
        data-editor-command-list=""
        d="M12 10v9m0-9l3 3m-3-3l-3 3m8.5 2c1.519 0 2.5-1.231 2.5-2.75a2.75 2.75 0 00-2.016-2.65A5 5 0 008.37 8.108a3.5 3.5 0 00-1.87 6.746"
      />
    ),
    download: <path data-editor-command-list="" d="M12 5v8.5m0 0l3-3m-3 3l-3-3M5 15v2a2 2 0 002 2h10a2 2 0 002-2v-2" />,
  };
  return (
    <svg
      data-editor-command-list=""
      xmlns="http://www.w3.org/2000/svg"
      width={name === 'trash' ? 24 : 20}
      height={name === 'trash' ? 24 : 20}
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      {paths[name]}
    </svg>
  );
}

export default function CommandList({
  visible = false,
  commandList = [],
  codeBits = 6,
  onUpdateCommandList,
  onClose,
  className = '',
  ...rest
}: CommandListProps) {
  const { t, locale } = useI18n();
  const [localList, setLocalList] = useState(() => cloneJson(commandList));
  const fullListRef = useRef(cloneJson(commandList));
  const [selectedCommand, setSelectedCommand] = useState(commandList.length ? 0 : null);
  const [editCommandEnabled, setEditCommandEnabled] = useState(false);
  const [editCommandField, setEditCommandField] = useState('');
  const [commandInputValue, setCommandInputValue] = useState('');
  const [isCreatingNew, setIsCreatingNew] = useState(false);
  const [isEditingName, setIsEditingName] = useState(false);
  const [editingCommandOriginalName, setEditingCommandOriginalName] = useState('');
  const [newCommandLines, setNewCommandLines] = useState('');
  const listRef = useRef<HTMLDivElement | null>(null);
  const previousBits = useRef(codeBits);
  const lastEmitted = useRef<string | null>(null);
  const incomingJson = JSON.stringify(commandList);
  const maxCommands = 2 ** codeBits;
  const matchingCommand = commandInputValue.trim()
    ? localList.find((command) => normalizeMnemonicToken(command.name, 'lower') === normalizeMnemonicToken(commandInputValue, 'lower'))
    : null;
  const selected = selectedCommand == null ? null : localList[selectedCommand];

  const emitUpdate = (next: RuntimeCommand[]) => {
    const seen = new Set();
    const duplicates = new Set();
    for (const command of next) {
      const key = normalizeMnemonicToken(command.name, 'lower');
      if (seen.has(key)) duplicates.add(command.name.trim());
      seen.add(key);
    }
    if (duplicates.size) {
      alert(t('commandList.errors.duplicatesFound', { names: [...duplicates].join(', ') }));
      return false;
    }
    const copy = cloneJson(next);
    lastEmitted.current = JSON.stringify(copy);
    onUpdateCommandList?.(copy);
    return true;
  };

  useEffect(() => {
    if (incomingJson === lastEmitted.current) return;
    const next = JSON.parse(incomingJson);
    fullListRef.current = cloneJson(next);
    setLocalList(next);
    setSelectedCommand((current) => (next.length ? Math.min(current ?? 0, next.length - 1) : null));
    setEditCommandEnabled(false);
    setIsEditingName(false);
  }, [incomingJson]);

  useEffect(() => {
    if (codeBits === previousBits.current) return;
    previousBits.current = codeBits;
    const next = cloneJson(fullListRef.current.slice(0, maxCommands));
    setLocalList(next);
    setSelectedCommand((current) => (next.length ? Math.min(current ?? 0, next.length - 1) : null));
    setEditCommandEnabled(false);
    emitUpdate(next);
  }, [codeBits]);

  const selectCommand = (index: number) => {
    setSelectedCommand(index);
    setCommandInputValue(localList[index]?.name || '');
    setIsCreatingNew(false);
    setEditCommandEnabled(false);
    setIsEditingName(false);
  };
  const changeInput = (value: string) => {
    setCommandInputValue(value);
    if (isEditingName) return;
    const index = localList.findIndex(
      (command) => normalizeMnemonicToken(command.name, 'lower') === normalizeMnemonicToken(value, 'lower')
    );
    setEditCommandEnabled(false);
    if (value.trim() && index >= 0) {
      setSelectedCommand(index);
      setIsCreatingNew(false);
    } else {
      setSelectedCommand(null);
      setIsCreatingNew(!!value.trim());
      if (!isCreatingNew) setNewCommandLines('');
    }
  };
  const saveCommand = () => {
    if (!selected) return;
    const next = localList.map((command, index) => (index === selectedCommand ? { ...command, lines: editCommandField } : command));
    fullListRef.current = fullListRef.current.map((command) =>
      command.name === selected.name ? { ...command, lines: editCommandField } : command
    );
    setLocalList(next);
    setEditCommandEnabled(false);
    emitUpdate(next);
  };
  const deleteCommand = () => {
    if (!selected) return;
    const next = localList.filter((_, index) => index !== selectedCommand);
    fullListRef.current = fullListRef.current.filter((command) => command.name !== selected.name);
    const nextIndex = next.length ? Math.min(selectedCommand ?? 0, next.length - 1) : null;
    setLocalList(next);
    setSelectedCommand(nextIndex);
    setCommandInputValue(nextIndex == null ? '' : next[nextIndex].name);
    setIsCreatingNew(false);
    setEditCommandEnabled(false);
    setIsEditingName(false);
    emitUpdate(next);
  };
  const cancelNameEdit = () => {
    setCommandInputValue(editingCommandOriginalName);
    setIsEditingName(false);
    setEditingCommandOriginalName('');
  };
  const confirmNameEdit = () => {
    const nextName = commandInputValue.trim();
    if (!nextName) {
      alert(t('commandList.errors.emptyName'));
      setCommandInputValue(editingCommandOriginalName);
      return;
    }
    const originalKey = normalizeMnemonicToken(editingCommandOriginalName, 'lower');
    const index = localList.findIndex((command) => normalizeMnemonicToken(command.name, 'lower') === originalKey);
    if (index < 0) {
      alert(t('commandList.errors.notFound'));
      cancelNameEdit();
      return;
    }
    if (
      fullListRef.current.some(
        (command) =>
          normalizeMnemonicToken(command.name, 'lower') !== originalKey &&
          normalizeMnemonicToken(command.name, 'lower') === normalizeMnemonicToken(nextName, 'lower')
      )
    ) {
      alert(t('commandList.errors.duplicate', { name: nextName }));
      setCommandInputValue(editingCommandOriginalName);
      return;
    }
    const rename = (command: RuntimeCommand) =>
      normalizeMnemonicToken(command.name, 'lower') === originalKey ? { ...command, name: nextName } : command;
    const next = localList.map(rename);
    fullListRef.current = fullListRef.current.map(rename);
    setLocalList(next);
    setCommandInputValue(nextName);
    setSelectedCommand(index);
    setIsEditingName(false);
    setEditingCommandOriginalName('');
    emitUpdate(next);
  };
  const addCommand = () => {
    if (localList.length >= maxCommands) {
      alert(t('commandList.errors.limitReached'));
      return;
    }
    const name = commandInputValue.trim();
    if (!name) {
      alert(t('commandList.errors.emptyName'));
      return;
    }
    if (fullListRef.current.some((command) => normalizeMnemonicToken(command.name, 'lower') === normalizeMnemonicToken(name, 'lower'))) {
      alert(t('commandList.errors.duplicate', { name }));
      return;
    }
    const command: RuntimeCommand = {
      name,
      args: 0,
      kind: 'exec',
      description: { [locale || 'pl']: t('commandList.commandDescription', { name }) },
      lines: newCommandLines || '',
    };
    const next = [...localList, command];
    fullListRef.current = [...fullListRef.current, cloneJson(command)];
    setLocalList(next);
    setSelectedCommand(next.length - 1);
    setCommandInputValue(name);
    setIsCreatingNew(false);
    setNewCommandLines('');
    emitUpdate(next);
    requestAnimationFrame(() =>
      listRef.current?.querySelectorAll('button')[next.length - 1]?.scrollIntoView({ behavior: 'smooth', block: 'nearest' })
    );
  };
  const loadCommandList = () => {
    const input = document.createElement('input');
    input.type = 'file';
    input.accept = '.lst,.json';
    input.onchange = async () => {
      const file = input.files?.[0];
      if (!file) return;
      try {
        const parsed = JSON.parse(await file.text());
        if (
          !Array.isArray(parsed) ||
          parsed.some(
            (command) => !command || typeof command.name !== 'string' || (command.lines != null && typeof command.lines !== 'string')
          )
        )
          throw new Error('Invalid command list');
        const normalized: RuntimeCommand[] = parsed.map((command: RuntimeCommand) => ({
          ...command,
          kind: command.kind || 'exec',
          lines: command.lines || '',
        }));
        const next = normalized.slice(0, maxCommands);
        if (!emitUpdate(next)) return;
        fullListRef.current = normalized;
        setLocalList(next);
        setSelectedCommand(next.length ? 0 : null);
        setCommandInputValue(next[0]?.name || '');
        setEditCommandEnabled(false);
        setIsEditingName(false);
        setIsCreatingNew(false);
      } catch {
        alert(t('commandList.errors.loadFailed'));
      }
    };
    input.click();
  };
  const downloadCommandList = () => {
    const url = URL.createObjectURL(new Blob([JSON.stringify(fullListRef.current, null, 2)], { type: 'application/json' }));
    const anchor = document.createElement('a');
    anchor.href = url;
    anchor.download = 'commandList.json';
    anchor.click();
    setTimeout(() => URL.revokeObjectURL(url), 0);
  };
  const placeholder = isEditingName
    ? t('commandList.placeholder.editName', { name: editingCommandOriginalName })
    : matchingCommand
      ? t('commandList.placeholder.editCommand', { name: matchingCommand.name })
      : t('commandList.placeholder.newName');

  if (!visible) return null;
  return (
    <div
      data-editor-command-list=""
      {...rest}
      className={`modal-overlay ${className}`}
      onClick={(event) => {
        if (event.target === event.currentTarget) onClose?.();
      }}
    >
      <div data-editor-command-list="" id="commandList" role="dialog" aria-modal="true" aria-labelledby="command-list-title">
        <div data-editor-command-list="" className="header">
          <h1 data-editor-command-list="" id="command-list-title">
            {t('commandList.title')}
          </h1>
          <button data-editor-command-list="" className="closeBtn closeButton" onClick={onClose} aria-label={t('commandList.closeAria')}>
            &times;
          </button>
        </div>
        <div data-editor-command-list="" id="commandListTable" ref={listRef}>
          <span data-editor-command-list="">
            {localList.length} / {maxCommands}
          </span>
          {localList.map((command, index) => (
            <button
              data-editor-command-list=""
              key={index}
              onClick={() => selectCommand(index)}
              className={`execution-btn execution-btn--run${selectedCommand === index ? ' selected' : ''}`}
            >
              <span data-editor-command-list="">{collectCommandAliases(command, { locale }).preferred[0]}</span>
            </button>
          ))}
        </div>
        <div data-editor-command-list="" className="right-panel">
          {(selected || isCreatingNew) && (
            <div data-editor-command-list="" id="commandDetails">
              <div data-editor-command-list="" className="roskazCode">
                {selected ? (
                  <textarea
                    data-editor-command-list=""
                    value={editCommandEnabled ? editCommandField : selected.lines || ''}
                    onChange={(event) => setEditCommandField(event.target.value)}
                    disabled={!editCommandEnabled}
                    aria-label={t('commandList.codePlaceholder')}
                  />
                ) : (
                  <textarea
                    data-editor-command-list=""
                    value={newCommandLines}
                    onChange={(event) => setNewCommandLines(event.target.value)}
                    placeholder={t('commandList.codePlaceholder')}
                  />
                )}
              </div>
            </div>
          )}
          <div data-editor-command-list="" className="actionButtons">
            {selected && (
              <div data-editor-command-list="" className="top-actions">
                <button
                  data-editor-command-list=""
                  onClick={deleteCommand}
                  title={t('commandList.deleteTitle')}
                  className="execution-btn execution-btn--run"
                >
                  <ActionIcon name="trash" />
                  <span data-editor-command-list="">{t('commandList.delete')}</span>
                </button>
                <button
                  data-editor-command-list=""
                  onClick={() => {
                    setEditCommandField(selected.lines || '');
                    setEditCommandEnabled(true);
                  }}
                  disabled={!selected || editCommandEnabled}
                  title={t('commandList.editTitle')}
                  className="execution-btn execution-btn--run"
                >
                  <span data-editor-command-list="">{t('commandList.edit')}</span>
                </button>
                <button
                  data-editor-command-list=""
                  onClick={saveCommand}
                  disabled={!editCommandEnabled}
                  title={t('commandList.saveTitle')}
                  className="execution-btn execution-btn--run"
                >
                  <span data-editor-command-list="">{t('commandList.save')}</span>
                </button>
              </div>
            )}
            <div data-editor-command-list="" className="commandInputSection">
              <div data-editor-command-list="" className="unifiedCommandInput">
                <input
                  data-editor-command-list=""
                  type="text"
                  value={commandInputValue}
                  onChange={(event) => changeInput(event.target.value)}
                  onKeyDown={(event) => {
                    if (!isEditingName) return;
                    if (event.key === 'Enter') {
                      event.preventDefault();
                      confirmNameEdit();
                    } else if (event.key === 'Escape') {
                      event.preventDefault();
                      cancelNameEdit();
                    }
                  }}
                  placeholder={placeholder}
                  className="commandInput"
                />
              </div>
              {isEditingName ? (
                <div data-editor-command-list="" className="editingButtons">
                  <button
                    data-editor-command-list=""
                    onClick={confirmNameEdit}
                    title={t('commandList.confirmTitle')}
                    className="execution-btn execution-btn--run"
                  >
                    <ActionIcon name="confirm" />
                    <span data-editor-command-list="">{t('commandList.confirm')}</span>
                  </button>
                  <button
                    data-editor-command-list=""
                    onClick={cancelNameEdit}
                    title={t('commandList.cancelTitle')}
                    className="execution-btn execution-btn--run"
                  >
                    <ActionIcon name="cancel" />
                    <span data-editor-command-list="">{t('commandList.cancel')}</span>
                  </button>
                </div>
              ) : matchingCommand ? (
                <button
                  data-editor-command-list=""
                  onClick={() => {
                    setIsEditingName(true);
                    setEditingCommandOriginalName(matchingCommand.name);
                  }}
                  title={t('commandList.editNameTitle')}
                  className="execution-btn execution-btn--run"
                >
                  <ActionIcon name="edit" />
                  <span data-editor-command-list="">{t('commandList.edit')}</span>
                </button>
              ) : (
                <button
                  data-editor-command-list=""
                  onClick={addCommand}
                  disabled={!commandInputValue.trim()}
                  title={t('commandList.addTitle')}
                  className="execution-btn execution-btn--run"
                >
                  <ActionIcon name="add" />
                  <span data-editor-command-list="">{t('commandList.add')}</span>
                </button>
              )}
            </div>
            <div data-editor-command-list="" className="fileActions">
              <button
                data-editor-command-list=""
                onClick={loadCommandList}
                title={t('commandList.loadTitle')}
                className="execution-btn execution-btn--run"
              >
                <ActionIcon name="load" />
                <span data-editor-command-list="">{t('commandList.load')}</span>
              </button>
              <button
                data-editor-command-list=""
                onClick={downloadCommandList}
                title={t('commandList.downloadTitle')}
                className="execution-btn execution-btn--run"
              >
                <ActionIcon name="download" />
                <span data-editor-command-list="">{t('commandList.download')}</span>
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

// src/components/CommandList.vue
<template>
  <div class="modal-overlay" v-if="visible" @click.self="$emit('close')">
    <div id="commandList">
      <div class="header">
        <h1>{{ $t('commandList.title') }}</h1>
        <button class="closeBtn closeButton" @click="$emit('close')" :aria-label="$t('commandList.closeAria')">&times;</button>
      </div>

      <div id="commandListTable">
        <span>{{ commandList.length }} / {{ Math.pow(2, codeBits) }}</span>
        <button
          v-for="(cmd, idx) in commandList"
          :key="idx"
          @click="editCommand(idx)"
          class="execution-btn execution-btn--run"
          :class="{ selected: selectedCommand === idx }"
        >
          <span>{{ cmd.name }}</span>
        </button>
      </div>

      <div class="right-panel">
        <div id="commandDetails" v-if="selectedCommand !== null || isCreatingNew">
          <div class="roskazCode">
            <textarea v-if="selectedCommand !== null && !editCommandEnabled" v-model="localList[selectedCommand].lines" disabled />
            <textarea v-else-if="selectedCommand !== null && editCommandEnabled" v-model="EditCommandField" />
            <textarea v-else v-model="newCommandLines" :placeholder="$t('commandList.codePlaceholder')" />
          </div>
        </div>

        <div class="actionButtons">
          <div class="top-actions" v-if="selectedCommand !== null">
            <button @click="deleteCommand" :title="$t('commandList.deleteTitle')" class="execution-btn execution-btn--run">
              <!-- ikona kosza -->
              <svg
                width="24"
                height="24"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                stroke-width="2"
                stroke-linecap="round"
                stroke-linejoin="round"
              >
                <polyline points="3 6 5 6 21 6" />
                <path d="M19 6l-1 14a2 2 0 0 1-2 2H8a2 2 0 0 1-2-2L5 6" />
                <path d="M10 11v6m4-6v6" />
                <path d="M15 6V4a2 2 0 0 0-2-2h-2a2 2 0 0 0-2 2v2" />
              </svg>
              <span>{{ $t('commandList.delete') }}</span>
            </button>

            <button
              class="execution-btn execution-btn--run"
              @click="onEdit"
              :disabled="!canEdit || editCommandEnabled"
              :title="$t('commandList.editTitle')"
            >
              <span>{{ $t('commandList.edit') }}</span>
            </button>

            <button
              class="execution-btn execution-btn--run"
              @click="onSave"
              :disabled="!editCommandEnabled"
              :title="$t('commandList.saveTitle')"
            >
              <span>{{ $t('commandList.save') }}</span>
            </button>
          </div>
          <div class="commandInputSection">
            <div class="unifiedCommandInput">
              <input
                type="text"
                v-model="commandInputValue"
                @keyup="handleKeyup"
                @keydown="handleKeydown"
                :placeholder="commandInputPlaceholder"
                class="commandInput"
              />
            </div>
            <div class="editingButtons" v-if="isEditingName">
              <button @click="confirmNameEdit" :title="$t('commandList.confirmTitle')" class="execution-btn execution-btn--run">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" stroke="currentColor" width="20" height="20" viewBox="0 0 24 24">
                  <polyline points="20 6 9 17 4 12" />
                </svg>
                <span>{{ $t('commandList.confirm') }}</span>
              </button>
              <button @click="cancelNameEdit" :title="$t('commandList.cancelTitle')" class="execution-btn execution-btn--run">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" stroke="currentColor" width="20" height="20" viewBox="0 0 24 24">
                  <path d="M18 6L6 18M6 6l12 12" />
                </svg>
                <span>{{ $t('commandList.cancel') }}</span>
              </button>
            </div>
            <button
              v-else-if="matchingCommand && !isEditingName"
              @click="startNameEdit"
              :title="$t('commandList.editNameTitle')"
              class="execution-btn execution-btn--run"
            >
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" stroke="currentColor" width="20" height="20" viewBox="0 0 24 24">
                <path
                  stroke-linecap="round"
                  stroke-linejoin="round"
                  stroke-width="2"
                  d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z"
                />
              </svg>
              <span>{{ $t('commandList.edit') }}</span>
            </button>
            <button
              v-else
              @click="handleAddCommand"
              :disabled="!commandInputValue.trim()"
              :title="$t('commandList.addTitle')"
              class="execution-btn execution-btn--run"
            >
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" stroke="currentColor" width="20" height="20" viewBox="0 0 24 24">
                <g stroke-width="2" stroke-linecap="round">
                  <path d="M12 16V8m4 4H8" />
                  <circle cx="12" cy="12" r="9" />
                </g>
              </svg>
              <span>{{ $t('commandList.add') }}</span>
            </button>
          </div>

          <div class="fileActions">
            <button @click="loadCommandList" :title="$t('commandList.loadTitle')" class="execution-btn execution-btn--run">
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" stroke="currentColor" width="20" height="20" viewBox="0 0 24 24">
                <path
                  stroke-linecap="round"
                  stroke-linejoin="round"
                  stroke-width="2"
                  d="M12 10v9m0-9l3 3m-3-3l-3 3m8.5 2c1.519 0 2.5-1.231 2.5-2.75a2.75 2.75 0 00-2.016-2.65A5 5 0 008.37 8.108a3.5 3.5 0 00-1.87 6.746"
                />
              </svg>
              <span>{{ $t('commandList.load') }}</span>
            </button>
            <button @click="downloadCommandList" :title="$t('commandList.downloadTitle')" class="execution-btn execution-btn--run">
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" stroke="currentColor" width="20" height="20" viewBox="0 0 24 24">
                <path
                  stroke-linecap="round"
                  stroke-linejoin="round"
                  stroke-width="2"
                  d="M12 5v8.5m0 0l3-3m-3 3l-3-3M5 15v2a2 2 0 002 2h10a2 2 0 002-2v-2"
                />
              </svg>
              <span>{{ $t('commandList.download') }}</span>
            </button>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import SegmentedToggle from './SegmentedToggle.vue';

export default {
  name: 'CommandList',
  components: { SegmentedToggle },
  props: {
    visible: { type: Boolean, default: false },
    commandList: { type: Array, required: true },
    codeBits: { type: Number, default: 6 },
  },
  emits: ['update:commandList', 'close'],
  data() {
    return {
      localList: JSON.parse(JSON.stringify(this.commandList)),
      fullCommandList: JSON.parse(JSON.stringify(this.commandList)),
      selectedCommand: this.commandList.length > 0 ? 0 : null,
      editCommandEnabled: false,
      EditCommandField: '',
      suppressEditCommit: false,
      commandInputValue: '',
      isAddingCommand: false,
      isCreatingNew: false,
      isEditingName: false,
      editingCommandOriginalName: '',
      newCommandLines: '',
    };
  },

  // there can be a situation where fullCommandList is deprecated after adding a new command
  // needs to be addressed, leaving due to the lack of time
  created() {
    this.fullCommandList = JSON.parse(JSON.stringify(this.commandList));
  },

  computed: {
    canEdit() {
      return this.selectedCommand !== null;
    },
    commandInputPlaceholder() {
      if (this.isEditingName) {
        return this.$t('commandList.placeholder.editName', { name: this.editingCommandOriginalName });
      }
      if (this.matchingCommand) {
        return this.$t('commandList.placeholder.editCommand', { name: this.matchingCommand.name });
      }
      return this.$t('commandList.placeholder.newName');
    },

    matchingCommand() {
      if (!this.commandInputValue.trim()) return null;

      // Normal matching
      const found = this.localList.find((cmd) => cmd.name.trim().toLowerCase() === this.commandInputValue.trim().toLowerCase());
      return found || null;
    },
  },
  watch: {
    commandList: {
      handler(newList) {
        if (this.isAddingCommand) {
          this.isAddingCommand = false;
          return;
        }

        this.localList = JSON.parse(JSON.stringify(newList));
        if (this.selectedCommand !== null && this.selectedCommand >= newList.length) {
          this.selectedCommand = newList.length > 0 ? newList.length - 1 : null;
        } else if (this.selectedCommand === null && newList.length > 0) {
          this.selectedCommand = 0;
        }
      },
      deep: true,
    },

    codeBits: {
      handler(newBits, oldBits) {
        const newMaxCommands = Math.pow(2, newBits);
        const oldMaxCommands = oldBits ? Math.pow(2, oldBits) : this.fullCommandList.length;

        if (newMaxCommands < oldMaxCommands) {
          // Bits decreased - trim visible list to new limit
          if (this.localList.length > newMaxCommands) {
            this.localList = this.localList.slice(0, newMaxCommands);

            // Adjust selected command if needed
            if (this.selectedCommand !== null && this.selectedCommand >= newMaxCommands) {
              this.selectedCommand = newMaxCommands > 0 ? newMaxCommands - 1 : null;
            }

            this.emitUpdate();
          }
        } else if (newMaxCommands > oldMaxCommands) {
          // Bits increased - restore instructions from full list up to new limit
          const commandsToRestore = Math.min(this.fullCommandList.length, newMaxCommands);
          this.localList = JSON.parse(JSON.stringify(this.fullCommandList.slice(0, commandsToRestore)));

          // Restore selected command if it was trimmed before
          if (this.selectedCommand === null && this.localList.length > 0) {
            this.selectedCommand = 0;
          }

          this.emitUpdate();
        }
      },
      immediate: false,
    },

    selectedCommand(newVal) {
      if (newVal === null) {
        return;
      }
      this.commandInputValue = this.localList[newVal].name;
      this.isCreatingNew = false;
    },

    matchingCommand(newCommand) {
      // Don't interfere when editing name
      if (this.isEditingName) return;

      if (newCommand) {
        // Found matching command - show its content
        const index = this.localList.findIndex((cmd) => cmd === newCommand);
        this.selectedCommand = index;
        this.isCreatingNew = false;
      } else if (this.commandInputValue.trim()) {
        // No matching command but input not empty - creating new
        this.selectedCommand = null;
        this.isCreatingNew = true;
        this.newCommandLines = '';
      } else {
        // Empty input
        this.selectedCommand = null;
        this.isCreatingNew = false;
      }
    },
    editCommandEnabled(val) {
      if (val) {
        this.EditCommandField = this.localList[this.selectedCommand]?.lines || '';
        return;
      }

      if (this.suppressEditCommit) {
        this.suppressEditCommit = false;
        this.EditCommandField = '';
        return;
      }

      if (this.selectedCommand !== null) {
        this.localList[this.selectedCommand].lines = this.EditCommandField;

        // Update the same command in fullCommandList
        const commandToUpdate = this.localList[this.selectedCommand];
        const fullListIndex = this.fullCommandList.findIndex((cmd) => cmd.name === commandToUpdate.name);
        if (fullListIndex !== -1) {
          this.fullCommandList[fullListIndex].lines = this.EditCommandField;
        }

        this.emitUpdate();
      }
    },
    localList: {
      handler(newList) {
        this.validateDuplicateNames();
      },
      deep: true,
    },
  },
  mounted() {
    if (this.localList.length === 0) {
      this.selectedCommand = null;
    } else if (this.selectedCommand === null) {
      this.selectedCommand = 0;
    }
  },
  methods: {
    onEdit() {
      this.editCommandEnabled = true;
    },
    onSave() {
      this.editCommandEnabled = false;
    },
    changeEditCommandEnabled() {
      this.editCommandEnabled = !this.editCommandEnabled;
    },
    validateDuplicateNames() {
      const names = this.localList.map((cmd) => cmd.name.trim()).filter((name) => name !== '');
      const duplicates = names.filter((name, index) => names.indexOf(name) !== index);

      if (duplicates.length > 0) {
        const uniqueDuplicates = [...new Set(duplicates)];
        console.warn(`Duplikaty nazw rozkazów: ${uniqueDuplicates.join(', ')}`);
      }
    },
    handleKeydown(event) {
      if (!this.isEditingName) {
        return;
      }

      if (event.key === 'Enter') {
        event.preventDefault();
        this.confirmNameEdit();
      } else if (event.key === 'Escape') {
        event.preventDefault();
        this.cancelNameEdit();
      }
    },
    cancelNameEdit() {
      this.commandInputValue = this.editingCommandOriginalName;
      this.isEditingName = false;
      this.editingCommandOriginalName = '';
    },
    startNameEdit() {
      if (!this.matchingCommand || !this.matchingCommand.name) {
        console.error('No matching command found or command has no name');
        alert(this.$t('commandList.errors.notFound'));
        return;
      }

      this.isEditingName = true;
      this.editingCommandOriginalName = this.matchingCommand.name;
    },
    confirmNameEdit() {
      const newName = this.commandInputValue.trim();
      console.log('confirmNameEdit called with:', newName);

      if (newName === '') {
        alert(this.$t('commandList.errors.emptyName'));
        this.commandInputValue = this.editingCommandOriginalName;
        return;
      }

      const commandToEdit = this.localList.find((cmd) => cmd.name.trim().toLowerCase() === this.editingCommandOriginalName.toLowerCase());

      if (!commandToEdit) {
        alert(this.$t('commandList.errors.notFound'));
        this.cancelNameEdit();
        return;
      }

      if (newName !== this.editingCommandOriginalName) {
        // Check for duplicates (excluding current command) in both lists
        const otherCommands = this.localList.filter((cmd) => cmd !== commandToEdit);
        const otherFullCommands = this.fullCommandList.filter(
          (cmd) => cmd.name.trim().toLowerCase() !== this.editingCommandOriginalName.toLowerCase()
        );

        const duplicate =
          otherCommands.find((cmd) => cmd.name.trim().toLowerCase() === newName.toLowerCase()) ||
          otherFullCommands.find((cmd) => cmd.name.trim().toLowerCase() === newName.toLowerCase());

        if (duplicate) {
          alert(this.$t('commandList.errors.duplicate', { name: newName }));
          this.commandInputValue = this.editingCommandOriginalName;
          return;
        }

        commandToEdit.name = newName;

        // Update the same command in fullCommandList
        const fullListCommand = this.fullCommandList.find(
          (cmd) => cmd.name.trim().toLowerCase() === this.editingCommandOriginalName.toLowerCase()
        );
        if (fullListCommand) {
          fullListCommand.name = newName;
        }

        this.emitUpdate();
      }

      this.isEditingName = false;
      this.editingCommandOriginalName = '';

      const newIndex = this.localList.findIndex((cmd) => cmd === commandToEdit);
      if (newIndex !== -1) {
        this.selectedCommand = newIndex;
      }
    },
    handleAddCommand() {
      if (this.localList.length >= Math.pow(2, this.codeBits)) {
        alert(this.$t('commandList.errors.limitReached'));
        return;
      }

      const newCommandName = this.commandInputValue.trim();

      if (newCommandName === '') {
        alert(this.$t('commandList.errors.emptyName'));
        return;
      }

      if (this.matchingCommand) {
        alert(this.$t('commandList.errors.duplicate', { name: newCommandName }));
        return;
      }

      const rawLocale = this.$i18n?.locale;
      const locale = typeof rawLocale === 'string' ? rawLocale : rawLocale?.value || 'pl';
      const newCommand = {
        name: newCommandName,
        args: 0,
        description: { [locale]: this.$t('commandList.commandDescription', { name: newCommandName }) },
        lines: this.newCommandLines || '',
      };

      this.localList.push(newCommand);
      this.fullCommandList.push(JSON.parse(JSON.stringify(newCommand)));

      const newIndex = this.localList.length - 1;
      this.selectedCommand = newIndex;
      this.isCreatingNew = false;
      this.newCommandLines = '';

      this.isAddingCommand = true;
      this.emitUpdate();

      this.$nextTick(() => {
        const commandButtons = document.querySelectorAll('#commandListTable > button');
        if (commandButtons[newIndex]) {
          commandButtons[newIndex].scrollIntoView({ behavior: 'smooth', block: 'nearest' });
        }
      });
    },

    loadCommandList() {
      const input = document.createElement('input');
      input.type = 'file';
      input.accept = '.lst,.json';
      input.onchange = (e) => {
        const file = e.target.files[0];
        const reader = new FileReader();
        reader.onload = (ev) => {
          try {
            const parsed = JSON.parse(ev.target.result);

            const maxCommands = Math.pow(2, this.codeBits);
            this.fullCommandList = parsed;
            this.localList = parsed.slice(0, maxCommands);

            if (this.localList.length > 0) {
              this.selectedCommand = 0;
              this.editCommandEnabled = false;
            } else {
              this.selectedCommand = null;
            }

            this.emitUpdate();
          } catch {
            alert(this.$t('commandList.errors.loadFailed'));
          }
        };
        reader.readAsText(file);
      };
      input.click();
    },
    downloadCommandList() {
      const data = JSON.stringify(this.fullCommandList, null, 2);
      const blob = new Blob([data], { type: 'application/json' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = 'commandList.json';
      a.click();
      URL.revokeObjectURL(url);
    },
    editCommand(index) {
      this.selectedCommand = index;
      this.editCommandEnabled = false;
    },
    deleteCommand() {
      if (this.selectedCommand === null) return;

      if (this.editCommandEnabled) {
        this.suppressEditCommit = true;
        this.editCommandEnabled = false;
      }

      const deletedIndex = this.selectedCommand;
      const commandToDelete = this.localList[this.selectedCommand];

      this.localList.splice(this.selectedCommand, 1);

      const fullListIndex = this.fullCommandList.findIndex(
        (cmd) => cmd.name === commandToDelete.name && cmd.lines === commandToDelete.lines
      );
      if (fullListIndex !== -1) {
        this.fullCommandList.splice(fullListIndex, 1);
      }

      if (this.localList.length === 0) {
        this.selectedCommand = null;
        this.commandInputValue = '';
        this.isCreatingNew = false;
      } else if (deletedIndex >= this.localList.length) {
        this.selectedCommand = this.localList.length - 1;
      } else {
        this.selectedCommand = deletedIndex;
      }

      this.emitUpdate();
    },
    emitUpdate() {
      const names = this.localList.map((cmd) => cmd.name.trim()).filter((name) => name !== '');
      const duplicates = names.filter((name, index) => names.indexOf(name) !== index);

      if (duplicates.length > 0) {
        const uniqueDuplicates = [...new Set(duplicates)];
        alert(this.$t('commandList.errors.duplicatesFound', { names: uniqueDuplicates.join(', ') }));
        return;
      }

      this.$emit('update:commandList', JSON.parse(JSON.stringify(this.localList)));
    },
  },
};
</script>

<style scoped>
.modal-overlay {
  position: fixed;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  background-color: rgba(0, 0, 0, 0.5);
  display: flex;
  justify-content: center;
  align-items: center;
  z-index: 99;
}
#commandList {
  z-index: 100;
  display: grid;
  grid-template-areas:
    'header header'
    'list right-panel';
  grid-template-rows: auto 1fr;
  grid-template-columns: 250px 1fr;
  gap: 1rem;
  border: 1px solid var(--panelOutlineColor, black);
  background-color: var(--panelBackgroundColor, white);
  color: var(--fontColor, black);
  border-radius: var(--default-border-radius, 0.25rem);
  box-shadow: 0 0 1rem rgba(0, 0, 0, 0.5);
  padding: 1rem;
  overflow: hidden;
  resize: both;
  width: 800px;
  max-width: 90vw;
  height: 90vh;
}

@media (max-width: 675px) {
  #commandList {
    grid-template-areas:
      'header header'
      'right-panel right-panel'
      'list list';
    grid-template-rows: auto auto auto;
    grid-template-columns: autos;
  }
}

body.darkMode #commandList {
  box-shadow: 0 0 1rem rgba(0, 0, 0, 0.8);
}

.header {
  grid-area: header;
  display: flex;
  justify-content: center;
  align-items: center;
  position: relative;
  padding: 0 0 1rem 0;
  border-bottom: 1px solid var(--panelOutlineColor, black);
}

.header h1 {
  margin: 0;
  font-size: 1.5rem;
  text-align: center;
  color: var(--fontColor, black);
}

.closeButton {
  position: absolute;
  right: 0;
  top: 0%;
}

#commandListTable {
  grid-area: list;
  display: flex;
  flex-direction: column;
  gap: 0.5rem;
  overflow-y: auto;
  padding-right: 0.5rem;
}

#commandListTable > span {
  color: var(--fontColor, black);
  font-size: 0.9rem;
  opacity: 0.7;
  margin-bottom: 0.5rem;
  padding: 0 0.5rem;
}

body.darkMode #commandListTable > button:hover {
  box-shadow: 0 2px 4px rgba(0, 0, 0, 0.3);
}

body.darkMode #commandListTable > button.selected {
  box-shadow: 0 2px 8px rgba(74, 158, 255, 0.4);
}

.right-panel {
  grid-area: right-panel;
  display: flex;
  flex-direction: column;
  gap: 1rem;
  padding-right: 0.5rem;
  min-width: 0;
}

#commandDetails {
  display: flex;
  flex-direction: column;
  flex-grow: 1;
  min-height: 0;
}

#commandDetails > .buttons {
  display: none;
}

#commandDetails .roskazCode {
  display: flex;
  flex-direction: column;
  justify-content: stretch;
  align-items: stretch;
  flex-grow: 1;
}

#commandDetails .roskazCode textarea {
  margin: 5px;
  width: 100%;
  flex-grow: 1;
  min-height: 150px;
  resize: none;
  padding: 0.75rem;
  background-color: var(--panelBackgroundColor, white);
  color: var(--fontColor, black);
  border-radius: 4px;
  font-family: 'Courier New', monospace;
  font-size: 14px;
  line-height: 1.4;
  transition: all 0.2s ease;
}

#commandDetails .roskazCode textarea:focus {
  outline: none;
  border-color: #003c7d;
  box-shadow: 0 0 0 2px #003c7d;
}

body.darkMode #commandDetails .roskazCode textarea:focus {
  box-shadow: 0 0 0 2px #003c7d;
}

#commandDetails .roskazCode textarea:disabled {
  opacity: 0.6;
  cursor: not-allowed;
  background-color: var(--buttonBackgroundColor, #f5f5f5);
}

body.darkMode #commandDetails .roskazCode textarea:disabled {
  opacity: 0.5;
}

.actionButtons {
  display: flex;
  flex-direction: column;
  gap: 1rem;
}

.top-actions {
  display: flex;
  justify-content: flex-end;
  align-items: center;
  gap: 1rem;
}

@media (max-width: 675px) {
  .top-actions {
    justify-content: center;
    gap: 0.5rem;
  }
}

.top-actions > button {
  height: 20px;
}

.top-actions > button:first-child:hover {
  background: #ff4444;
  color: white;
  border-color: #ff4444;
}

.commandInputSection {
  display: flex;
  align-items: center;
  gap: 0.75rem;
}

.unifiedCommandInput {
  display: flex;
  flex-direction: column;
  gap: 0.5rem;
  flex-grow: 1;
}

.editingButtons {
  display: flex;
  gap: 0.5rem;
}

.commandInput {
  flex: 1;
  margin-left: 5px;
  padding: 1rem;
  border: 1px solid var(--panelOutlineColor, black);
  border-radius: 4px;
  background-color: var(--panelBackgroundColor, white);
  color: var(--fontColor, black);
  font-size: 14px;
  transition: all 0.2s ease;
}

@media (max-width: 675px) {
  .commandInputSection {
    gap: 1rem;
    justify-content: end;
    flex-wrap: wrap;
  }
}

.commandInput:focus {
  outline: none;
  border-color: #003c7d;
  box-shadow: 0 0 0 2px #003c7d;
}

body.darkMode .commandInput:focus {
  box-shadow: 0 0 0 2px rgba(74, 158, 255, 0.3);
}

.fileActions {
  display: flex;
  justify-content: center;
  gap: 1rem;
}

.actionButtons button svg {
  width: 20px;
  height: 20px;
}

.actionButtons button:disabled {
  opacity: 0.5;
  cursor: not-allowed;
  background: var(--buttonBackgroundColor, white) !important;
  color: #999 !important;
  border-color: #ddd !important;
  transform: none;
  box-shadow: none;
}

body.darkMode .commandInputSection button:hover,
body.darkMode .fileActions button:hover {
  box-shadow: 0 2px 4px rgba(0, 0, 0, 0.3);
}
</style>
