// src/components/Console/Console.jsx
'use client';

import { useEffect, useRef, useState } from 'react';
import { useI18n } from '@/i18n';
import { ErrorLevel, ErrorLevelColor } from '@/errors';

const pad = (number) => String(number).padStart(2, '0');
function formatTimestamp(timestamp) {
  const date = new Date(timestamp);
  const time = [pad(date.getHours()), pad(date.getMinutes()), pad(date.getSeconds())].join(':');
  if (date.toDateString() === new Date().toDateString()) return time;
  return `${[date.getFullYear(), pad(date.getMonth() + 1), pad(date.getDate())].join('-')} ${time}`;
}
function getLogLevel(log) {
  if (log.error?.level) return log.error.level;
  if (log.level) return log.level;
  switch (log.class?.toLowerCase()) {
    case 'error': case 'parser-error': return ErrorLevel.ERROR;
    case 'warning': return ErrorLevel.WARNING;
    default: return ErrorLevel.INFO;
  }
}
const hasErrorDetails = (log) => !!(log.error?.code || log.error?.hint || log.error?.loc || log.error?.frame || log.error?.timestamp);
function Icon({ children }) { return <svg data-editor-console="" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">{children}</svg>; }

export default function Console({ logs = [], onClose, onClear, className = '', ...rest }) {
  const { t } = useI18n();
  const [expandedEntries, setExpandedEntries] = useState(() => new Set());
  const contentRef = useRef(null);
  const followsBottom = useRef(true);
  const previousLogsLength = useRef(logs.length);
  const scrollTo = (bottom) => contentRef.current?.scrollTo({ top: bottom ? contentRef.current.scrollHeight : 0, behavior: 'smooth' });
  useEffect(() => {
    if (logs.length > previousLogsLength.current && followsBottom.current) scrollTo(true);
    if (!logs.length) setExpandedEntries(new Set());
    previousLogsLength.current = logs.length;
  }, [logs.length]);
  const toggleDetails = (index) => setExpandedEntries((current) => {
    const next = new Set(current);
    if (next.has(index)) next.delete(index); else next.add(index);
    return next;
  });

  return <div data-editor-console="" {...rest} id="console" className={`futuristic-console ${className}`}>
    <div data-editor-console="" className="console-header">
      <div data-editor-console="" className="header-left"><div data-editor-console="" className="status-indicator" /><span data-editor-console="" className="console-title">{t('console.title')}</span></div>
      <div data-editor-console="" className="header-center">
        <button data-editor-console="" onClick={() => scrollTo(false)} className="scroll-top-btn" title={t('console.scrollTop')}><Icon><path data-editor-console="" d="M18 15l-6-6-6 6" /></Icon></button>
        <button data-editor-console="" onClick={() => scrollTo(true)} className="scroll-bottom-btn" title={t('console.scrollBottom')}><Icon><path data-editor-console="" d="M6 9l6 6 6-6" /></Icon></button>
        <button data-editor-console="" onClick={onClear} className="clear-btn" title={t('console.clear')}><Icon><path data-editor-console="" d="M3 6h18" /><path data-editor-console="" d="M19 6v14c0 1-1 2-2 2H7c-1 0-2-1-2-2V6" /><path data-editor-console="" d="M8 6V4c0-1 1-2 2-2h4c1 0 2 1 2 2v2" /></Icon></button>
      </div>
      <div data-editor-console="" className="header-right"><span data-editor-console="" className="entry-count">{t('console.entryCount', { count: logs.length })}</span><button data-editor-console="" onClick={onClose} className="close-btn" title={t('console.close')}><Icon><path data-editor-console="" d="M18 6l-12 12" /><path data-editor-console="" d="M6 6l12 12" /></Icon></button></div>
    </div>
    <div data-editor-console="" className="console-content" ref={contentRef} onScroll={(event) => { const element = event.currentTarget; followsBottom.current = element.scrollTop + element.clientHeight >= element.scrollHeight - 10; }}>
      {logs.map((log, index) => {
        const level = getLogLevel(log);
        const color = ErrorLevelColor[level] || ErrorLevelColor[ErrorLevel.INFO];
        const hasDetails = hasErrorDetails(log);
        const error = log.error;
        return <div data-editor-console="" key={index} className={`console-entry level-${level.toLowerCase()}${hasDetails ? ' has-details' : ''}`}>
          <div data-editor-console="" className="entry-header" onClick={() => hasDetails && toggleDetails(index)}>
            <div data-editor-console="" className="entry-meta"><div data-editor-console="" className="severity-indicator" style={{ backgroundColor: color }} /><span data-editor-console="" className="timestamp">{formatTimestamp(log.timestamp)}</span><span data-editor-console="" className="level-badge" style={{ color }}>{level || log.class || 'INFO'}</span></div>
            <div data-editor-console="" className="entry-content"><div data-editor-console="" className="message-line"><span data-editor-console="" className="terminal-symbol">{'>_'}</span><span data-editor-console="" className="message">{log.message || error?.message || t('console.unknownMessage')}</span></div>
              {hasDetails && <button data-editor-console="" className={`details-toggle${expandedEntries.has(index) ? ' expanded' : ''}`} aria-expanded={expandedEntries.has(index)} aria-label={t('console.detailContext')} onClick={(event) => { event.stopPropagation(); toggleDetails(index); }}><Icon><circle data-editor-console="" cx="12" cy="12" r="10" /><path data-editor-console="" d="M12 16v-4" /><path data-editor-console="" d="M12 8h.01" /></Icon></button>}
            </div>
          </div>
          {expandedEntries.has(index) && hasDetails && <div data-editor-console="" className="entry-details"><div data-editor-console="" className="details-content">
            {error.code && <div data-editor-console="" className="detail-section"><span data-editor-console="" className="detail-label">{t('console.detailCode')}</span><code data-editor-console="" className="detail-value">{error.code}</code></div>}
            {error.hint && <div data-editor-console="" className="detail-section"><span data-editor-console="" className="detail-label">{t('console.detailHint')}</span><div data-editor-console="" className="detail-value hint-text">{error.hint}</div></div>}
            {error.loc && <div data-editor-console="" className="detail-section"><span data-editor-console="" className="detail-label">{t('console.detailLocation')}</span><code data-editor-console="" className="detail-value">{t('console.locationValue', { line: error.loc.line, column: error.loc.col })}</code></div>}
            {error.frame && <div data-editor-console="" className="detail-section code-frame"><span data-editor-console="" className="detail-label">{t('console.detailContext')}</span><pre data-editor-console="" className="detail-value code-block">{error.frame}</pre></div>}
            {error.timestamp && <div data-editor-console="" className="detail-section"><span data-editor-console="" className="detail-label">{t('console.detailOccurred')}</span><span data-editor-console="" className="detail-value">{new Date(error.timestamp).toLocaleString()}</span></div>}
          </div></div>}
        </div>;
      })}
    </div>
  </div>;
}

// src/components/Console.vue
<template>
  <div id="console" class="futuristic-console">
    <div class="console-header">
      <div class="header-left">
        <div class="status-indicator"></div>
        <span class="console-title">{{ $t('console.title') }}</span>
      </div>
      <div class="header-center">
        <button @click="scrollToTop" class="scroll-top-btn" :title="$t('console.scrollTop')">
          <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
            <path d="M18 15l-6-6-6 6" />
          </svg>
        </button>
        <button @click="scrollToBottom" class="scroll-bottom-btn" :title="$t('console.scrollBottom')">
          <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
            <path d="M6 9l6 6 6-6" />
          </svg>
        </button>
        <button @click="clearConsole" class="clear-btn" :title="$t('console.clear')">
          <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
            <path d="M3 6h18" />
            <path d="M19 6v14c0 1-1 2-2 2H7c-1 0-2-1-2-2V6" />
            <path d="M8 6V4c0-1 1-2 2-2h4c1 0 2 1 2 2v2" />
          </svg>
        </button>
      </div>
      <div class="header-right">
        <span class="entry-count">{{ $t('console.entryCount', { count: logs.length }) }}</span>
        <button @click="closeConsole" class="close-btn" :title="$t('console.close')">
          <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
            <path d="M18 6l-12 12" />
            <path d="M6 6l12 12" />
          </svg>
        </button>
      </div>
    </div>

    <div class="console-content" ref="consoleContentRef">
      <div v-for="(log, i) in logs" :key="i" :class="['console-entry', getLogLevelClass(log), { 'has-details': hasErrorDetails(log) }]">
        <div class="entry-header" @click="hasErrorDetails(log) ? toggleDetails(i) : null">
          <div class="entry-meta">
            <div class="severity-indicator" :style="{ backgroundColor: getLogColor(log) }"></div>
            <span class="timestamp">{{ fmt(log.timestamp) }}</span>
            <span class="level-badge" :style="{ color: getLogColor(log) }">
              {{ getDisplayLevel(log) }}
            </span>
          </div>

          <div class="entry-content">
            <div class="message-line">
              <span class="terminal-symbol">>_</span>
              <span class="message">{{ getMainMessage(log) }}</span>
            </div>

            <button
              v-if="hasErrorDetails(log)"
              class="details-toggle"
              :class="{ expanded: expandedEntries.has(i) }"
              @click.stop="toggleDetails(i)"
            >
              <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                <circle cx="12" cy="12" r="10" />
                <path d="M12 16v-4" />
                <path d="M12 8h.01" />
              </svg>
            </button>
          </div>
        </div>

        <div v-if="expandedEntries.has(i) && hasErrorDetails(log)" class="entry-details">
          <div class="details-content">
            <div v-if="getErrorCode(log)" class="detail-section">
              <span class="detail-label">{{ $t('console.detailCode') }}</span>
              <code class="detail-value">{{ getErrorCode(log) }}</code>
            </div>

            <div v-if="getErrorHint(log)" class="detail-section">
              <span class="detail-label">{{ $t('console.detailHint') }}</span>
              <div class="detail-value hint-text">{{ getErrorHint(log) }}</div>
            </div>

            <div v-if="getErrorLocation(log)" class="detail-section">
              <span class="detail-label">{{ $t('console.detailLocation') }}</span>
              <code class="detail-value">{{ getErrorLocation(log) }}</code>
            </div>

            <div v-if="getErrorFrame(log)" class="detail-section code-frame">
              <span class="detail-label">{{ $t('console.detailContext') }}</span>
              <pre class="detail-value code-block">{{ getErrorFrame(log) }}</pre>
            </div>

            <div v-if="getErrorTimestamp(log)" class="detail-section">
              <span class="detail-label">{{ $t('console.detailOccurred') }}</span>
              <span class="detail-value">{{ formatDetailedTimestamp(getErrorTimestamp(log)) }}</span>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, nextTick, toRefs, watch } from 'vue';
import { useI18n } from 'vue-i18n';
import { ErrorLevel, ErrorLevelColor } from '../errors';

const props = defineProps({
  logs: { type: Array, default: () => [] },
});

const emit = defineEmits(['close', 'clear']);
const expandedEntries = ref(new Set());
const consoleContentRef = ref(null);
const { t } = useI18n();

const pad = (n) => String(n).padStart(2, '0');

const fmt = (ts) => {
  const d = new Date(ts);
  const today = new Date().toDateString() === d.toDateString();
  const YMD = [d.getFullYear(), pad(d.getMonth() + 1), pad(d.getDate())].join('-');
  const HMS = [pad(d.getHours()), pad(d.getMinutes()), pad(d.getSeconds())].join(':');

  return today ? HMS : `${YMD} ${HMS}`;
};

const formatDetailedTimestamp = (timestamp) => {
  return new Date(timestamp).toLocaleString();
};

const getLogLevelClass = (log) => {
  // Map legacy class names and new error levels
  const level = getLogLevel(log);
  return `level-${level.toLowerCase()}`;
};

const getLogLevel = (log) => {
  // Check if it's a BaseAppError with level property
  if (log.error?.level) {
    return log.error.level;
  }

  // Check direct level property
  if (log.level) {
    return log.level;
  }

  // Map legacy class names
  const legacyClass = log.class?.toLowerCase();
  switch (legacyClass) {
    case 'error':
    case 'błąd':
    case 'błąd parsera kodu':
      return ErrorLevel.ERROR;
    case 'warning':
    case 'ostrzeżenie':
      return ErrorLevel.WARNING;
    case 'info':
    case 'system':
    case 'kompilator rozkazów':
      return ErrorLevel.INFO;
    default:
      return ErrorLevel.INFO;
  }
};

const getLogColor = (log) => {
  const level = getLogLevel(log);
  return ErrorLevelColor[level] || ErrorLevelColor[ErrorLevel.INFO];
};

const getDisplayLevel = (log) => {
  const level = getLogLevel(log);
  return level || log.class || 'INFO';
};

const getMainMessage = (log) => {
  return log.message || log.error?.message || t('console.unknownMessage');
};

const hasErrorDetails = (log) => {
  return !!(log.error?.code || log.error?.hint || log.error?.loc || log.error?.frame || log.error?.timestamp);
};

const getErrorCode = (log) => {
  return log.error?.code;
};

const getErrorHint = (log) => {
  return log.error?.hint;
};

const getErrorLocation = (log) => {
  const loc = log.error?.loc;
  if (!loc) return null;
  return t('console.locationValue', { line: loc.line, column: loc.col });
};

const getErrorFrame = (log) => {
  return log.error?.frame;
};

const getErrorTimestamp = (log) => {
  return log.error?.timestamp;
};

const toggleDetails = (index) => {
  if (expandedEntries.value.has(index)) {
    expandedEntries.value.delete(index);
  } else {
    expandedEntries.value.add(index);
  }
};

const closeConsole = () => {
  emit('close');
};

const clearConsole = () => {
  emit('clear');
};

const scrollToTop = () => {
  if (consoleContentRef.value) {
    consoleContentRef.value.scrollTo({
      top: 0,
      behavior: 'smooth',
    });
  }
};

const scrollToBottom = () => {
  if (consoleContentRef.value) {
    nextTick(() => {
      consoleContentRef.value.scrollTo({
        top: consoleContentRef.value.scrollHeight,
        behavior: 'smooth',
      });
    });
  }
};

// Auto-scroll to bottom when new logs are added (only if user is already at bottom)
const { logs } = toRefs(props);
watch(
  logs,
  (newLogs, oldLogs) => {
    if (newLogs.length > (oldLogs?.length || 0) && consoleContentRef.value) {
      const element = consoleContentRef.value;
      const isAtBottom = element.scrollTop + element.clientHeight >= element.scrollHeight - 10;

      if (isAtBottom) {
        nextTick(() => {
          scrollToBottom();
        });
      }
    }
  },
  { deep: true }
);
</script>
