// src/Components/MemoryContent.tsx
'use client';

import useWindowWidth from '@/Shared/Hooks/UseWindowWidth';
import { useI18n } from '@/I18n/Index';
import { toSigned, toUnsigned } from '@/Shared/Utils/Numbers';
import { collectCommandAliases } from '@/Shared/Utils/CommandMnemonics';
import { useMachineServices } from '@/State/MachineContext';
import type { MemoryContentProps, MemoryInputProps } from '@/Types/Components';
import { Fragment, useEffect, useState } from 'react';
import RegisterComponent from './Registers/RegisterComponent';
import SignalButton from './SignalButton';

function MemoryInput({ value, min, max, label, onChange }: MemoryInputProps) {
  const [draft, setDraft] = useState(String(value));
  useEffect(() => setDraft(String(value)), [value]);
  return (
    <input
      inputMode="numeric"
      type="number"
      className="hoverInput"
      aria-label={label}
      value={draft}
      min={min}
      max={max}
      onChange={(event) => {
        const raw = event.target.value;
        setDraft(raw);
        if (raw.trim() === '' || raw.trim() === '-') return;
        if (!onChange(raw)) setDraft(String(value));
      }}
      onBlur={() => {
        if (draft.trim() === '' || draft.trim() === '-') {
          onChange('0');
          setDraft('0');
        } else setDraft(String(value));
      }}
    />
  );
}

export default function MemoryContent({
  A,
  S,
  mem,
  signals,
  formatNumber,
  decToCommand,
  decToArgument,
  aFormat,
  sFormat,
  signedDec = false,
  wordBits = 8,
  onUpdateA,
  onUpdateS,
  onUpdateMem,
  onClickItem,
  onUpdateAFormat,
  onUpdateSFormat,
}: MemoryContentProps) {
  const width = useWindowWidth();
  const isMobile = width < 1080;
  const { t, locale } = useI18n();
  const { showToast } = useMachineServices();
  const modulo = 2 ** wordBits;
  const min = signedDec ? -modulo / 2 : 0;
  const max = signedDec ? modulo / 2 - 1 : modulo - 1;
  const displayValue = (raw: number) => (signedDec ? toSigned(raw, wordBits) : toUnsigned(raw, wordBits));
  const updateMemoryValue = (raw: string, index: number) => {
    const value = parseInt(raw, 10);
    if (Number.isNaN(value)) return false;
    if (value < min || value > max) {
      showToast?.(t('memory.outOfRange', { val: value, min, max, bits: wordBits }));
      return false;
    }
    const next = [...mem];
    next[index] = toUnsigned(value, wordBits);
    onUpdateMem?.(next);
    return true;
  };

  return (
    <div id="memory">
      {!isMobile && (
        <SignalButton
          id="wea"
          signal={signals.wea}
          label="wea"
          divClassNames="pathDownOnRight"
          spanClassNames="arrowRightOnBottom"
          onClick={() => onClickItem?.('wea')}
        />
      )}
      <RegisterComponent
        classNames="register"
        id="aRegister"
        label="A"
        model={A}
        onUpdateModel={onUpdateA}
        numberFormat={aFormat}
        onUpdateNumberFormat={onUpdateAFormat}
      />
      <div id="memoryTable">
        <div className="scrollWrapper">
          <div className="memoryContainer">
            <span className="label">{t(width < 1400 ? 'memory.labelShort' : 'memory.labelFull')}</span>
            <span className="label">{t('memory.value')}</span>
            <span className="label">{t('memory.code')}</span>
            <span className="label">{t('memory.address')}</span>
            {mem.map((value, index) => {
              const selected = A === index ? 'selected' : '';
              const command = decToCommand(value);
              return (
                <Fragment key={index}>
                  <span className={selected}>{formatNumber(index)}</span>
                  <div className={`inputWrapper${selected ? ' selected' : ''}`}>
                    <span>{formatNumber(value)}</span>
                    <MemoryInput
                      value={displayValue(value)}
                      min={min}
                      max={max}
                      label={t('memory.cellLabel', { index })}
                      onChange={(raw) => updateMemoryValue(raw, index)}
                    />
                  </div>
                  <span className={selected}>{command ? collectCommandAliases(command, { locale }).preferred[0] : t('memory.empty')}</span>
                  <span className={selected}>{formatNumber(decToArgument(value))}</span>
                </Fragment>
              );
            })}
          </div>
        </div>
      </div>
      <RegisterComponent
        classNames="register"
        id="sRegister"
        label="S"
        model={S}
        onUpdateModel={onUpdateS}
        numberFormat={sFormat}
        onUpdateNumberFormat={onUpdateSFormat}
      />
      {!isMobile && (
        <>
          <div id="operations">
            <SignalButton
              id="czyt"
              signal={signals.czyt}
              label="czyt"
              spanClassNames="lineLeftOnBottom"
              onClick={() => onClickItem?.('czyt')}
            />
            <SignalButton
              id="pisz"
              signal={signals.pisz}
              label="pisz"
              spanClassNames="lineLeftOnBottom"
              onClick={() => onClickItem?.('pisz')}
            />
          </div>
          <div className="signals">
            <SignalButton
              id="wes"
              signal={signals.wes}
              label="wes"
              divClassNames="pathUpOnRight"
              spanClassNames="arrowRightOnBottom"
              onClick={() => onClickItem?.('wes')}
            />
            <SignalButton
              id="wys"
              signal={signals.wys}
              label="wys"
              divClassNames="pathDownOnLeft"
              spanClassNames="lineLeftOnBottom"
              onClick={() => onClickItem?.('wys')}
            />
          </div>
        </>
      )}
    </div>
  );
}

// src/components/MemoryContent.vue
﻿<template>
  <div id="memory">
    <SignalButton
      id="wea"
      v-if="!isMobile"
      :signal="signals.wea"
      label="wea"
      divClassNames="pathDownOnRight"
      spanClassNames="arrowRightOnBottom"
      @click="handleClick('wea')"
    />
    <RegisterComponent
      classNames="register"
      id="aRegister"
      label="A"
      :model="A"
      @update:model="$emit('update:A', $event)"
      :number-format="aFormat"
      @update:number-format="$emit('update:aFormat', $event)"
    />
    <div id="memoryTable">
      <div class="scrollWrapper">
        <div class="memoryContainer">
          <span class="label">{{ memoryLabel }}</span>
          <span class="label">Wartość</span>
          <span class="label">Kod</span>
          <span class="label">Adres</span>
          <template v-for="(value, index) in mem" :key="index">
            <span :class="{ selected: A === index }">{{ formatNumber(index) }}</span>
            <div :class="{ selected: A === index }" class="inputWrapper">
              <span>{{ formatNumber(mem[index]) }}</span>
              <input
                inputmode="numeric"
                type="number"
                class="hoverInput"
                :value="displayValue(mem[index])"
                :min="signedDec ? -(1 << (wordBits - 1)) : 0"
                :max="signedDec ?  ((1 << (wordBits - 1)) - 1) : wordMask()"
                @input="updateMemoryValue($event, index)"
                @blur="onMemoryBlur($event, index)"
              />
            </div>
            <span :class="{ selected: A === index }">
              {{ decToCommand(value) ? decToCommand(value).name : 'EMPTY' }}
            </span>
            <span :class="{ selected: A === index }">
              {{ formatNumber(decToArgument(value)) }}
            </span>
          </template>
        </div>
      </div>
    </div>
    <RegisterComponent
      classNames="register"
      id="sRegister"
      label="S"
      :model="S"
      @update:model="$emit('update:S', $event)"
      :number-format="sFormat"
      @update:number-format="$emit('update:sFormat', $event)"
    />
    <div id="operations" v-if="!isMobile">
      <SignalButton id="czyt" :signal="signals.czyt" label="czyt" spanClassNames="lineLeftOnBottom" @click="handleClick('czyt')" />
      <SignalButton id="pisz" :signal="signals.pisz" label="pisz" spanClassNames="lineLeftOnBottom" @click="handleClick('pisz')" />
    </div>
    <div class="signals" v-if="!isMobile">
      <SignalButton
        id="wes"
        v-if="!isMobile"
        :signal="signals.wes"
        label="wes"
        divClassNames="pathUpOnRight"
        spanClassNames="arrowRightOnBottom"
        @click="handleClick('wes')"
      />
      <SignalButton
        id="wys"
        v-if="!isMobile"
        :signal="signals.wys"
        label="wys"
        divClassNames="pathDownOnLeft"
        spanClassNames="lineLeftOnBottom"
        @click="handleClick('wys')"
      />
    </div>
  </div>
</template>
<script>
import SignalButton from './SignalButton.vue';
import RegisterComponent from './RegisterComponent.vue';
export default {
  name: 'MemoryContent',
  inject: {
    validateRegisterValue: {
      default: null,
    },
    showToast: {
      default: null,
    },
    getMaxValueForRegister: {
      default: null,
    },
  },
  props: {
    A: {
      type: Number,
      required: true,
    },
    S: {
      type: Number,
      required: true,
    },
    mem: {
      type: Array,
      required: true,
    },
    signals: {
      type: Object,
      required: true,
    },
    formatNumber: {
      type: Function,
      required: true,
    },
    decToCommand: {
      type: Function,
      required: true,
    },
    decToArgument: {
      type: Function,
      required: true,
    },
    aFormat: {
      type: String,
      required: true,
    },
    sFormat: {
      type: String,
      required: true,
    },
    signedDec: {
      type: Boolean,
      default: false
    },
    wordBits:  {
      type: Number,
      default: 8
    },
  },
  emits: ['update:A', 'update:S', 'update:mem', 'clickItem', 'update:aFormat', 'update:sFormat'],
  components: {
    SignalButton,
    RegisterComponent,
  },
  data() {
    return {
      windowWidth: window.innerWidth,
    };
  },
  computed: {
    isMobile() {
      return this.windowWidth < 1080;
    },
    memoryLabel() {
      return this.windowWidth < 1400 ? 'Adr.' : 'Adres pamięci';
    },
  },
  methods: {
    wordMask() {
      return (1 << this.wordBits) - 1;
    },
    toSigned(v) {
      const mod = 1 << this.wordBits;
      const sign = 1 << (this.wordBits - 1);
      const m = v & (mod - 1);
      return (m & sign) ? (m - mod) : m;
    },
    displayValue(raw) {
      return this.signedDec ? this.toSigned(raw) : (raw & this.wordMask());
    },
    handleClick(id) {
      this.$emit('clickItem', id);
    },
    updateWindowWidth() {
      this.windowWidth = window.innerWidth;
    },
    updateMemoryValue(event, index) {
      const txt = String(event.target.value).trim();
      if (txt === '' || txt === '-' ) return;
      const val = parseInt(txt, 10);
      if (Number.isNaN(val)) {
        event.target.value = this.displayValue(this.mem[index]);
        return;
      }
      if (this.validateRegisterValue) {
        const ok = this.validateRegisterValue(
          val,
          'memory',
          `Pamięć[${index}]`,
        );
        if (!ok) {
          event.target.value = this.displayValue(this.mem[index]);
          return;
        }
      } else {
        const min = this.signedDec ? -(1 << (this.wordBits - 1)) : 0;
        const max = this.signedDec ?  ((1 << (this.wordBits - 1)) - 1) : this.wordMask();
        if (val < min || val > max) {
          if (this.showToast) {
            this.showToast(
              `Wartość ${val} poza zakresem ${min}..${max} (słowo ${this.wordBits}-bit${this.wordBits===1?'owe':'owe'}).`
            );
          }
          event.target.value = this.displayValue(this.mem[index]);
          return;
        }
      }
      let stored;
      if (this.signedDec && val < 0) {
        stored = (val + (1 << this.wordBits)) & this.wordMask();
      } else {
        stored = val & this.wordMask();
      }
      const newMem = [...this.mem];
      newMem[index] = stored;
      this.$emit('update:mem', newMem);
    },
    onMemoryBlur(event, index) {
      const txt = String(event.target.value).trim();
      if (txt === '' || txt === '-') {
        const newMem = [...this.mem];
        newMem[index] = 0;
        this.$emit('update:mem', newMem);
        event.target.value = this.displayValue(0);
      } else {
        event.target.value = this.displayValue(this.mem[index]);
      }
    },
  },
  mounted() {
    window.addEventListener('resize', this.updateWindowWidth);
  },
  beforeUnmount() {
    window.removeEventListener('resize', this.updateWindowWidth);
  },
};
</script>
