// src/Components/SignalButton.tsx
'use client';

import type { SignalButtonProps } from '@/Types/Components';
export default function SignalButton({
  id,
  signal,
  label,
  divClassNames = '',
  spanClassNames = '',
  className = '',
  onClick,
  style,
}: SignalButtonProps) {
  return (
    <div
      id={id}
      className={['signal', 'impulse', divClassNames, className, signal ? 'active' : ''].filter(Boolean).join(' ')}
      style={style}
      role="button"
      tabIndex={0}
      aria-label={label}
      aria-pressed={Boolean(signal)}
      onClick={onClick}
      onKeyDown={(event) => {
        if (event.key === 'Enter' || event.key === ' ') {
          event.preventDefault();
          onClick?.(event);
        }
      }}
    >
      <span className={spanClassNames}>{label}</span>
    </div>
  );
}

// src/components/SignalButton.vue
<template>
    <div
      :id="id"
      :class="['signal', 'impulse', divClassNames, { active: signal }]">
      <span :class="[spanClassNames]">{{ label }}</span>
    </div>
  </template>
  
  <script>
  export default {
    name: "SignalButton",
    props: {
      id: {
        type: String,
        required: true
      },
      signal: {
        type: Boolean,
        required: true
      },
      label: {
        type: String,
        required: true
      },
      divClassNames: {
        type: String,
        default: ''
      },
      spanClassNames: {
        type: String,
        default: ''
      }
    },
  };
  </script>
