// src/components/registers/XRegisterSection.tsx
import type { XRegisterSectionProps } from '@/types/components';
import RegisterComponent from './RegisterComponent';
import SignalButton from '../SignalButton';

export default function XRegisterSection({
  visible,
  X,
  signals,
  numberFormat,
  onUpdateX,
  onUpdateNumberFormat,
  onClickItem,
}: XRegisterSectionProps) {
  if (!visible) return null;
  return (
    <div id="xRegister">
      <SignalButton
        id="wyx"
        signal={signals.wyx}
        label="wyx"
        divClassNames="pathUpOnRight"
        spanClassNames="lineRightOnBottom"
        onClick={() => onClickItem?.('wyx')}
      />
      <RegisterComponent
        label="X"
        model={X}
        onUpdateModel={onUpdateX}
        numberFormat={numberFormat}
        onUpdateNumberFormat={onUpdateNumberFormat}
      />
      <SignalButton
        id="wex"
        signal={signals.wex}
        label="wex"
        divClassNames="pathDownOnLeft"
        spanClassNames="arrowLeftOnBottom"
        onClick={() => onClickItem?.('wex')}
      />
    </div>
  );
}

// src/components/XRegisterSection.vue
<template>
  <div v-if="visible" id="xRegister">
    <SignalButton
      id="wyx"
      :signal="signals.wyx"
      label="wyx"
      divClassNames="pathUpOnRight"
      spanClassNames="lineRightOnBottom"
      @click="handleClick('wyx')"
    />
    <RegisterComponent
      label="X"
      :model="X"
      @update:model="$emit('update:X', $event)"
      :number-format="numberFormat"
      @update:number-format="$emit('update:numberFormat', $event)"
    />
    <SignalButton
      id="wex"
      :signal="signals.wex"
      label="wex"
      divClassNames="pathDownOnLeft"
      spanClassNames="arrowLeftOnBottom"
      @click="handleClick('wex')"
    />
  </div>
</template>

<script>
import SignalButton from './SignalButton.vue';
import RegisterComponent from './RegisterComponent.vue';

export default {
  name: 'XRegisterSection',
  props: {
    visible: Boolean,
    X: Number,
    signals: Object,
    numberFormat: {
      type: String,
      required: true,
    },
  },
  emits: ['clickItem', 'update:X', 'update:numberFormat'],
  components: {
    SignalButton,
    RegisterComponent,
  },
  methods: {
    handleClick(id) {
      this.$emit('clickItem', id);
    },
  },
};
</script>
