// src/components/APRegisterSection.vue
<template>
  <div v-if="visible" id="apRegister">
    <SignalButton
      id="wyap"
      :signal="signals.wyap"
      label="wyap"
      divClassNames="pathDownOnRight"
      spanClassNames="lineRightOnBottom"
      @click="handleClick('wyap')"
    />
    <RegisterComponent
      label="AP"
      :model="AP"
      @update:model="$emit('update:AP', $event)"
      :number-format="numberFormat"
      @update:number-format="$emit('update:numberFormat', $event)"
    />
  </div>
</template>

<script>
import SignalButton from './SignalButton.vue';
import RegisterComponent from './RegisterComponent.vue';

export default {
  name: 'APRegisterSection',
  props: {
    visible: Boolean,
    AP: Number,
    signals: Object,
    numberFormat: {
      type: String,
      required: true,
    },
  },
  emits: ['clickItem', 'update:AP', 'update:numberFormat'],
  components: {
    SignalButton,
    RegisterComponent,
  },
  methods: {
    handleClick(id) {
      this.$emit('clickItem', id);
    },
  },
};
</script>

// src/components/registers/APRegisterSection.tsx
import type { APRegisterSectionProps } from '@/types/components';
import RegisterComponent from './RegisterComponent';
import SignalButton from '../SignalButton';

export default function APRegisterSection({
  visible,
  AP,
  signals,
  numberFormat,
  onUpdateAP,
  onUpdateNumberFormat,
  onClickItem,
}: APRegisterSectionProps) {
  if (!visible) return null;
  return (
    <div id="apRegister">
      <SignalButton
        id="wyap"
        signal={signals.wyap}
        label="wyap"
        divClassNames="pathDownOnRight"
        spanClassNames="lineRightOnBottom"
        onClick={() => onClickItem?.('wyap')}
      />
      <RegisterComponent
        label="AP"
        model={AP}
        onUpdateModel={onUpdateAP}
        numberFormat={numberFormat}
        onUpdateNumberFormat={onUpdateNumberFormat}
      />
    </div>
  );
}
