// src/components/YRegisterSection.vue
<template>
  <div v-if="visible" id="yRegister">
    <SignalButton
      id="wyy"
      :signal="signals.wyy"
      label="wyy"
      divClassNames="pathUpOnRight"
      spanClassNames="lineRightOnBottom"
      @click="handleClick('wyy')"
    />
    <RegisterComponent
      label="Y"
      :model="Y"
      @update:model="$emit('update:Y', $event)"
      :number-format="numberFormat"
      @update:number-format="$emit('update:numberFormat', $event)"
    />
    <SignalButton
      id="wey"
      :signal="signals.wey"
      label="wey"
      divClassNames="pathDownOnLeft"
      spanClassNames="arrowLeftOnBottom"
      @click="handleClick('wey')"
    />
  </div>
</template>

<script>
import SignalButton from './SignalButton.vue';
import RegisterComponent from './RegisterComponent.vue';

export default {
  name: 'YRegisterSection',
  props: {
    visible: Boolean,
    Y: Number,
    signals: Object,
    numberFormat: {
      type: String,
      required: true,
    },
  },
  emits: ['clickItem', 'update:Y', 'update:numberFormat'],
  components: {
    SignalButton,
    RegisterComponent,
  },
  methods: {
    handleClick(id) {
      this.$emit('clickItem', id);
    },
  },
};
</script>

// src/components/registers/YRegisterSection.tsx
import type { YRegisterSectionProps } from '@/types/components';
import RegisterComponent from './RegisterComponent';
import SignalButton from '../SignalButton';

export default function YRegisterSection({
  visible,
  Y,
  signals,
  numberFormat,
  onUpdateY,
  onUpdateNumberFormat,
  onClickItem,
}: YRegisterSectionProps) {
  if (!visible) return null;
  return (
    <div id="yRegister">
      <SignalButton
        id="wyy"
        signal={signals.wyy}
        label="wyy"
        divClassNames="pathUpOnRight"
        spanClassNames="lineRightOnBottom"
        onClick={() => onClickItem?.('wyy')}
      />
      <RegisterComponent
        label="Y"
        model={Y}
        onUpdateModel={onUpdateY}
        numberFormat={numberFormat}
        onUpdateNumberFormat={onUpdateNumberFormat}
      />
      <SignalButton
        id="wey"
        signal={signals.wey}
        label="wey"
        divClassNames="pathDownOnLeft"
        spanClassNames="arrowLeftOnBottom"
        onClick={() => onClickItem?.('wey')}
      />
    </div>
  );
}
