// src/components/Settings/ColorPicker.vue
﻿<template>
  <div class="cp-root" @dragstart.prevent>
    <!-- KoĹ‚o barw -->
    <div class="cp-wheel-wrap" :style="{ width: size + 'px', height: size + 'px' }">
      <canvas
        ref="wheel"
        class="cp-wheel"
        :width="size * scale"
        :height="size * scale"
        :style="{ width: size + 'px', height: size + 'px' }"
      ></canvas>

      <div class="cp-indicator" :style="{ left: indicator.x + 'px', top: indicator.y + 'px', background: hex }"></div>

      <div ref="hit" class="cp-hitbox" @pointerdown="startPick" @pointermove="movePick" @pointerup="endPick" @pointercancel="endPick"></div>
    </div>

    <!-- Suwak jasnoĹ›ci koloru (HSV: V) -->
    <div class="cp-section">
      <div class="cp-label">{{ $t('colorPicker.colorBrightness') }}</div>
      <div class="cp-bar" :style="{ background: `linear-gradient(90deg, #000, ${hexPure})` }"></div>
      <input class="cp-range" type="range" min="0" max="1" step="0.001" v-model.number="hsv.v" @input="updateFromHSV" />
      <div class="cp-mini">{{ Math.round(hsv.v * 100) }}%</div>
    </div>

    <!-- Suwak mocy LED (global brightness) -->
    <div class="cp-section">
      <div class="cp-label">{{ $t('colorPicker.ledBrightness') }}</div>
      <div class="cp-bar cp-bar-grey"></div>
      <input class="cp-range" type="range" min="0" max="1" step="0.001" :value="brightnessLocal" @input="onPowerInput($event)" />
      <div class="cp-mini">{{ Math.round(brightnessLocal * 100) }}%</div>
    </div>

    <!-- PrĂłbki -->
    <div class="cp-swatches">
      <button v-for="c in swatches" :key="c" class="cp-swatch" :style="{ background: c }" @click="applyHex(c)"></button>
    </div>

    <!-- PodglÄ…d -->
    <div class="cp-readout">
      <div class="cp-current" :style="{ background: hex }"></div>
      <div class="cp-text">
        <div class="cp-line">{{ hex }}</div>
        <div class="cp-line">
          rgb({{ Math.round(rgb.r * brightnessLocal) }}, {{ Math.round(rgb.g * brightnessLocal) }},
          {{ Math.round(rgb.b * brightnessLocal) }})
        </div>
        <div class="cp-line">hsv({{ hsv.h.toFixed(0) }}, {{ Math.round(hsv.s * 100) }}%, {{ Math.round(hsv.v * 100) }}%)</div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, reactive, watch, onMounted, computed } from 'vue';

const props = defineProps({
  modelValue: { type: String, default: '#ff00ff' },
  size: { type: Number, default: 240 },
  brightness: { type: Number, default: 1 },
});
const emit = defineEmits(['update:modelValue', 'update:brightness', 'change']);

const wheel = ref(null);
const hit = ref(null);
const size = props.size;
const scale = window.devicePixelRatio || 1;

// HSV + RGB
const hsv = reactive({ h: 300, s: 0.5, v: 1 });
const rgb = reactive({ r: 255, g: 0, b: 255 });

// Hex z zastosowanÄ… jasnoĹ›ciÄ… (do wyĹ›wietlania)
const hex = computed(() => {
  const s = brightnessLocal.value;
  const finalRgb = {
    r: Math.round(rgb.r * s),
    g: Math.round(rgb.g * s),
    b: Math.round(rgb.b * s),
  };
  return rgbToHex(finalRgb);
});
const hexPure = computed(() => rgbToHex(hsvToRgb(hsv.h, hsv.s, 1)));

// wskaĹşnik
const indicator = reactive({ x: size / 2, y: size / 2 });

// przeciÄ…ganie
let picking = false;
let rafId = 0;
let lastEvent = null;

const swatches = [
  '#ffffff',
  '#000000',
  '#ff0000',
  '#ffa500',
  '#ffff00',
  '#00ff00',
  '#00ffff',
  '#0000ff',
  '#ff00ff',
  '#c0c0c0',
  '#808080',
  '#8b4513',
  '#ff69b4',
  '#7fff00',
  '#40e0d0',
  '#8a2be2',
];

// global brightness
const brightnessLocal = ref(clamp01(props.brightness));
watch(
  () => props.brightness,
  (v) => {
    brightnessLocal.value = clamp01(v);
  }
);

onMounted(() => {
  drawWheel();
  applyHex(isValidHex(props.modelValue) ? props.modelValue : '#ff00ff');
});

function drawWheel() {
  const ctx = wheel.value.getContext('2d');
  const W = Math.round(size * scale);
  const H = W;
  const cx = W / 2 - 3;
  const cy = H / 2 - 3;
  const r = W / 2 - 0.5; // klucz: -0.5 usuwa pĂłĹ‚przezroczysty ring
  const img = ctx.createImageData(W, H);

  for (let y = 0; y < H; y++) {
    for (let x = 0; x < W; x++) {
      const dx = x - cx,
        dy = y - cy;
      const dist = Math.hypot(dx, dy);
      const i = (y * W + x) * 4;
      if (dist <= r) {
        let ang = Math.atan2(dy, dx);
        if (ang < 0) ang += Math.PI * 2;
        const h = (ang * 180) / Math.PI;
        const s = Math.min(1, dist / r);
        const { r: rr, g: gg, b: bb } = hsvToRgb(h, s, 1);
        img.data[i] = rr;
        img.data[i + 1] = gg;
        img.data[i + 2] = bb;
        img.data[i + 3] = 255;
      } else {
        img.data[i + 3] = 0;
      }
    }
  }
  ctx.putImageData(img, 0, 0);
  updateIndicator();
}

function localPoint(e) {
  const r = (hit.value || wheel.value).getBoundingClientRect();
  return { x: e.clientX - r.left, y: e.clientY - r.top };
}

// pointer capture + rAF
function startPick(e) {
  e.preventDefault();
  picking = true;
  try {
    e.currentTarget.setPointerCapture(e.pointerId);
  } catch {}
  lastEvent = e;
  schedule();
}
function movePick(e) {
  if (!picking && e.buttons === 0) return;
  e.preventDefault();
  lastEvent = e;
  schedule();
}
function endPick(e) {
  picking = false;
  try {
    e.currentTarget.releasePointerCapture(e.pointerId);
  } catch {}
  lastEvent = null;
}
function schedule() {
  if (rafId) return;
  rafId = requestAnimationFrame(() => {
    rafId = 0;
    if (!lastEvent) return;
    const p = localPoint(lastEvent);
    const cx = size / 2,
      cy = size / 2;
    const dx = p.x - cx,
      dy = p.y - cy;
    const r = size / 2;
    const dist = Math.min(Math.hypot(dx, dy), r);
    let ang = Math.atan2(dy, dx);
    if (ang < 0) ang += Math.PI * 2;
    hsv.h = (ang * 180) / Math.PI;
    hsv.s = dist / r;
    updateFromHSV();
  });
}

function updateFromHSV() {
  const { r, g, b } = hsvToRgb(hsv.h, hsv.s, hsv.v);
  rgb.r = r;
  rgb.g = g;
  rgb.b = b;
  updateIndicator();

  // Zastosuj jasnoĹ›Ä‡ bezpoĹ›rednio do RGB dla hex
  const s = brightnessLocal.value;
  const finalRgb = {
    r: Math.round(rgb.r * s),
    g: Math.round(rgb.g * s),
    b: Math.round(rgb.b * s),
  };
  const finalHex = rgbToHex(finalRgb);

  emit('update:modelValue', finalHex);
  emit('change', {
    hex: finalHex,
    rgb: finalRgb,
    hsv: { ...hsv },
    brightness: s,
    rgbScaled: finalRgb,
    pwm: finalRgb,
    baseRgb: { ...rgb }, // Oryginalne RGB bez jasnoĹ›ci
  });
}

function updateIndicator() {
  const r = (size / 2) * hsv.s;
  const rad = (hsv.h * Math.PI) / 180;
  const cx = size / 2,
    cy = size / 2;
  indicator.x = cx + r * Math.cos(rad);
  indicator.y = cy + r * Math.sin(rad);
}

function onPowerInput(e) {
  const v = clamp01(parseFloat(e.target.value));
  brightnessLocal.value = v;
  emit('update:brightness', v);

  // Zastosuj jasnoĹ›Ä‡ bezpoĹ›rednio do RGB dla hex
  const finalRgb = {
    r: Math.round(rgb.r * v),
    g: Math.round(rgb.g * v),
    b: Math.round(rgb.b * v),
  };
  const finalHex = rgbToHex(finalRgb);

  emit('update:modelValue', finalHex);
  emit('change', {
    hex: finalHex,
    rgb: finalRgb,
    hsv: { ...hsv },
    brightness: v,
    rgbScaled: finalRgb,
    pwm: finalRgb,
    baseRgb: { ...rgb }, // Oryginalne RGB bez jasnoĹ›ci
  });
}

function applyHex(h) {
  const parsed = hexToRgb(h);
  if (!parsed) return;

  // Ustaw jasnoĹ›Ä‡ na maksimum i uĹĽyj podanego hex jako bazowego koloru
  brightnessLocal.value = 1;
  emit('update:brightness', 1);

  const hv = rgbToHsv(parsed.r, parsed.g, parsed.b);
  hsv.h = hv.h;
  hsv.s = hv.s;
  hsv.v = hv.v;
  updateFromHSV();
}

/* util */
function hsvToRgb(h, s, v) {
  const c = v * s,
    x = c * (1 - Math.abs(((h / 60) % 2) - 1)),
    m = v - c;
  let r = 0,
    g = 0,
    b = 0;
  if (0 <= h && h < 60) {
    r = c;
    g = x;
    b = 0;
  } else if (60 <= h && h < 120) {
    r = x;
    g = c;
    b = 0;
  } else if (120 <= h && h < 180) {
    r = 0;
    g = c;
    b = x;
  } else if (180 <= h && h < 240) {
    r = 0;
    g = x;
    b = c;
  } else if (240 <= h && h < 300) {
    r = x;
    g = 0;
    b = c;
  } else {
    r = c;
    g = 0;
    b = x;
  }
  return { r: Math.round((r + m) * 255), g: Math.round((g + m) * 255), b: Math.round((b + m) * 255) };
}
function rgbToHsv(r, g, b) {
  r /= 255;
  g /= 255;
  b /= 255;
  const max = Math.max(r, g, b),
    min = Math.min(r, g, b),
    d = max - min;
  let h = 0;
  if (d !== 0) {
    if (max === r) h = 60 * (((g - b) / d) % 6);
    else if (max === g) h = 60 * ((b - r) / d + 2);
    else h = 60 * ((r - g) / d + 4);
  }
  if (h < 0) h += 360;
  const s = max === 0 ? 0 : d / max,
    v = max;
  return { h, s, v };
}
function rgbToHex({ r, g, b }) {
  const to = (x) => x.toString(16).padStart(2, '0');
  return `#${to(r)}${to(g)}${to(b)}`;
}
function hexToRgb(h) {
  const m = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(h || '');
  if (!m) return null;
  return { r: parseInt(m[1], 16), g: parseInt(m[2], 16), b: parseInt(m[3], 16) };
}
function isValidHex(h) {
  return /^#?[0-9a-fA-F]{6}$/.test(h || '');
}
function clamp01(x) {
  return Math.max(0, Math.min(1, Number.isFinite(x) ? x : 0));
}
</script>

<style scoped>
.cp-root {
  color: var(--fontColor);
  font-family: inherit;
  user-select: none;
}

.cp-wheel-wrap {
  position: relative;
  margin: 0 auto 12px auto;
  cursor: crosshair;

  /* obramowanie i maska KOĹA na wrapperze */
  border: 3px solid #003c7d;
  border-radius: 50%;
  overflow: hidden; /* utnie wszystko poza koĹ‚em */
  background-clip: padding-box;
}

.cp-wheel {
  display: block;
  border: none;
  border-radius: 0; /* juĹĽ niepotrzebne */
}

.cp-hitbox {
  position: absolute;
  inset: 0;
  touch-action: none;
}

/* interakcja po caĹ‚ym kole */
.cp-indicator {
  position: absolute;
  width: 14px;
  height: 14px;
  border: 3px solid #003c7d;
  box-shadow: 0 0 0 1px rgba(0, 0, 0, 0.6);
  border-radius: 9999px;
  transform: translate(-50%, -50%);
  pointer-events: none;
}

.cp-section {
  margin-top: 14px;
}

.cp-label {
  font-size: 12px;
  opacity: 0.85;
  margin-bottom: 6px;
}

.cp-bar {
  height: 8px;
  border-radius: 9999px;
  box-shadow: inset 0 0 0 1px var(--panelOutlineColor);
}

.cp-bar-grey {
  background: linear-gradient(90deg, #222, #eee);
}

.cp-mini {
  font-size: 12px;
  opacity: 0.8;
  margin-top: 6px;
}

.cp-range {
  width: 100%;
  margin-top: 8px;
  appearance: none;
  height: 8px;
  background: transparent;
}

.cp-range::-webkit-slider-runnable-track {
  height: 8px;
  border-radius: 9999px;
  background: transparent;
}

.cp-range::-webkit-slider-thumb {
  appearance: none;
  width: 18px;
  height: 18px;
  border-radius: 9999px;
  background: #fff;
  border: 3px solid #003c7d;
  margin-top: -5px;
}

.cp-range::-moz-range-track {
  height: 8px;
  border-radius: 9999px;
  background: transparent;
}

.cp-range::-moz-range-thumb {
  width: 18px;
  height: 18px;
  border-radius: 9999px;
  background: #fff;
  border: 2px solid #003c7d;
}

.cp-swatches {
  margin-top: 14px;
  display: grid;
  grid-template-columns: repeat(8, 1fr);
  gap: 8px;
}

.cp-swatch {
  width: 26px;
  height: 26px;
  border-radius: 9999px;
  border: 3px solid #003c7d;
  cursor: pointer;
}

.cp-readout {
  margin-top: 14px;
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 10px;
}

.cp-current {
  width: 28px;
  height: 28px;
  border-radius: 9999px;
  border: 1px solid var(--panelOutlineColor);
}

.cp-text {
  font-size: 12px;
  line-height: 1.25;
}

.cp-line {
  opacity: 0.9;
}
</style>

// src/components/Settings/ColorPicker.jsx
'use client';

import { useEffect, useRef, useState } from 'react';
import { useI18n } from '@/i18n';

const SWATCHES = [
  '#ffffff',
  '#000000',
  '#ff0000',
  '#ffa500',
  '#ffff00',
  '#00ff00',
  '#00ffff',
  '#0000ff',
  '#ff00ff',
  '#c0c0c0',
  '#808080',
  '#8b4513',
  '#ff69b4',
  '#7fff00',
  '#40e0d0',
  '#8a2be2',
];
const clamp01 = (value) => Math.max(0, Math.min(1, Number.isFinite(value) ? value : 0));

export function hsvToRgb(h, s, v) {
  const c = v * s,
    x = c * (1 - Math.abs(((h / 60) % 2) - 1)),
    m = v - c;
  const [r, g, b] = h < 60 ? [c, x, 0] : h < 120 ? [x, c, 0] : h < 180 ? [0, c, x] : h < 240 ? [0, x, c] : h < 300 ? [x, 0, c] : [c, 0, x];
  return { r: Math.round((r + m) * 255), g: Math.round((g + m) * 255), b: Math.round((b + m) * 255) };
}
export function rgbToHsv(r, g, b) {
  r /= 255;
  g /= 255;
  b /= 255;
  const max = Math.max(r, g, b),
    min = Math.min(r, g, b),
    d = max - min;
  let h = d === 0 ? 0 : max === r ? 60 * (((g - b) / d) % 6) : max === g ? 60 * ((b - r) / d + 2) : 60 * ((r - g) / d + 4);
  if (h < 0) h += 360;
  return { h, s: max === 0 ? 0 : d / max, v: max };
}
export function rgbToHex({ r, g, b }) {
  return `#${[r, g, b].map((value) => Math.round(value).toString(16).padStart(2, '0')).join('')}`;
}
export function hexToRgb(hex) {
  const match = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex || '');
  return match ? { r: parseInt(match[1], 16), g: parseInt(match[2], 16), b: parseInt(match[3], 16) } : null;
}
export function colorDataFromHSV(hsv, brightness) {
  const baseRgb = hsvToRgb(hsv.h, hsv.s, hsv.v);
  const rgb = Object.fromEntries(Object.entries(baseRgb).map(([key, value]) => [key, Math.round(value * brightness)]));
  return { hex: rgbToHex(rgb), rgb, hsv: { ...hsv }, brightness, rgbScaled: rgb, pwm: rgb, baseRgb };
}

export default function ColorPicker({
  modelValue = '#ff00ff',
  size = 240,
  brightness = 1,
  onUpdateModelValue,
  onUpdateBrightness,
  onChange,
}) {
  const { t } = useI18n();
  const wheel = useRef(null);
  const picking = useRef(false);
  const callbacks = useRef({ onUpdateModelValue, onUpdateBrightness, onChange });
  callbacks.current = { onUpdateModelValue, onUpdateBrightness, onChange };
  const [hsv, setHsv] = useState(() => {
    const rgb = hexToRgb(modelValue) || { r: 255, g: 0, b: 255 };
    return rgbToHsv(rgb.r, rgb.g, rgb.b);
  });
  const [power, setPower] = useState(clamp01(brightness));
  const data = colorDataFromHSV(hsv, power);
  const hexPure = rgbToHex(hsvToRgb(hsv.h, hsv.s, 1));
  const angle = (hsv.h * Math.PI) / 180;
  const indicator = { x: size / 2 + (size / 2) * hsv.s * Math.cos(angle), y: size / 2 + (size / 2) * hsv.s * Math.sin(angle) };
  useEffect(() => {
    setPower(clamp01(brightness));
  }, [brightness]);
  useEffect(() => {
    const canvas = wheel.current;
    const scale = Math.min(window.devicePixelRatio || 1, 3);
    const width = Math.round(size * scale);
    canvas.width = width;
    canvas.height = width;
    const context = canvas.getContext('2d');
    if (!context) return;
    const pixels = context.createImageData(width, width);
    const center = width / 2,
      radius = width / 2 - 0.5;
    for (let y = 0; y < width; y++)
      for (let x = 0; x < width; x++) {
        const dx = x - center,
          dy = y - center,
          distance = Math.hypot(dx, dy),
          offset = (y * width + x) * 4;
        if (distance > radius) continue;
        const hue = ((Math.atan2(dy, dx) * 180) / Math.PI + 360) % 360;
        const rgb = hsvToRgb(hue, Math.min(1, distance / radius), 1);
        pixels.data[offset] = rgb.r;
        pixels.data[offset + 1] = rgb.g;
        pixels.data[offset + 2] = rgb.b;
        pixels.data[offset + 3] = 255;
      }
    context.putImageData(pixels, 0, 0);
  }, [size]);
  useEffect(() => {
    const value = colorDataFromHSV(hsv, power);
    callbacks.current.onUpdateModelValue?.(value.hex);
    callbacks.current.onUpdateBrightness?.(power);
    callbacks.current.onChange?.(value);
  }, [hsv, power]);
  const pick = (event) => {
    const rect = event.currentTarget.getBoundingClientRect();
    const dx = ((event.clientX - rect.left) / rect.width) * size - size / 2,
      dy = ((event.clientY - rect.top) / rect.height) * size - size / 2;
    setHsv((previous) => ({
      ...previous,
      h: ((Math.atan2(dy, dx) * 180) / Math.PI + 360) % 360,
      s: Math.min(1, Math.hypot(dx, dy) / (size / 2)),
    }));
  };
  return (
    <div className="cp-root" data-component="ColorPicker" onDragStart={(event) => event.preventDefault()}>
      <div className="cp-wheel-wrap" style={{ width: size, height: size }}>
        <canvas ref={wheel} className="cp-wheel" style={{ width: size, height: size }} />
        <div className="cp-indicator" style={{ left: indicator.x, top: indicator.y, background: data.hex }} />
        <div
          className="cp-hitbox"
          onPointerDown={(event) => {
            event.preventDefault();
            picking.current = true;
            event.currentTarget.setPointerCapture?.(event.pointerId);
            pick(event);
          }}
          onPointerMove={(event) => {
            if (picking.current) pick(event);
          }}
          onPointerUp={(event) => {
            picking.current = false;
            if (event.currentTarget.hasPointerCapture?.(event.pointerId)) event.currentTarget.releasePointerCapture(event.pointerId);
          }}
          onPointerCancel={() => {
            picking.current = false;
          }}
        />
      </div>
      <div className="cp-section">
        <div className="cp-label">{t('colorPicker.colorBrightness')}</div>
        <div className="cp-bar" style={{ background: `linear-gradient(90deg, #000, ${hexPure})` }} />
        <input
          className="cp-range"
          type="range"
          aria-label={t('colorPicker.colorBrightness')}
          min="0"
          max="1"
          step="0.001"
          value={hsv.v}
          onChange={(event) => setHsv((previous) => ({ ...previous, v: Number(event.target.value) }))}
        />
        <div className="cp-mini">{Math.round(hsv.v * 100)}%</div>
      </div>
      <div className="cp-section">
        <div className="cp-label">{t('colorPicker.ledBrightness')}</div>
        <div className="cp-bar cp-bar-grey" />
        <input
          className="cp-range"
          type="range"
          aria-label={t('colorPicker.ledBrightness')}
          min="0"
          max="1"
          step="0.001"
          value={power}
          onChange={(event) => setPower(clamp01(Number(event.target.value)))}
        />
        <div className="cp-mini">{Math.round(power * 100)}%</div>
      </div>
      <div className="cp-swatches">
        {SWATCHES.map((color) => (
          <button
            type="button"
            key={color}
            className="cp-swatch"
            style={{ background: color }}
            aria-label={color}
            onClick={() => {
              const rgb = hexToRgb(color);
              setPower(1);
              setHsv(rgbToHsv(rgb.r, rgb.g, rgb.b));
            }}
          />
        ))}
      </div>
      <div className="cp-readout">
        <div className="cp-current" style={{ background: data.hex }} />
        <div className="cp-text">
          <div className="cp-line">{data.hex}</div>
          <div className="cp-line">
            rgb({data.rgb.r}, {data.rgb.g}, {data.rgb.b})
          </div>
          <div className="cp-line">
            hsv({hsv.h.toFixed(0)}, {Math.round(hsv.s * 100)}%, {Math.round(hsv.v * 100)}%)
          </div>
        </div>
      </div>
    </div>
  );
}
