// src/components/Settings/SettingsPanel.tsx
'use client';

import type { SavedColor } from '@/types/colors';
import CommandListIcon from '@/assets/svg/CommandListIcon';
import RefreshIcon from '@/assets/svg/RefreshIcon';
import SegmentedToggle from '@/components/SegmentedToggle';
import { useI18n } from '@/i18n';
import type { ColorSelection, ColorTarget } from '@/types/colors';
import type { Update } from '@/types/common';
import type { PendingColor, SettingsNumber, SettingsPanelProps, SwitchProps, ToggleOption, ToggleValue } from '@/types/components';
import type { ReactNode } from 'react';
import { useState } from 'react';
import ColorPickerPopup from './ColorPickerPopup';
import PeopleSection from './PeopleSection';

const BOOLEAN_KEYS = ['xRegister', 'yRegister', 'dl', 'jamlExtras', 'busConnectors', 'showInvisibleRegisters'] as const;
const GROUPS = {
  io: ['rbRegister', 'gRegister'],
  stack: ['wsRegister', 'wylsSignal'],
  interrupts: ['rzRegister', 'rpRegister', 'rmRegister', 'apRegister', 'rintSignal', 'eniSignal'],
};
const NUMBERS: readonly SettingsNumber[] = [
  ['codeBits', 'commandBits', 'bits.codeLabel', 'bits.codeHelp', 1, 16],
  ['addresBits', 'addresBits', 'bits.addressLabel', 'bits.addressHelp', 1, 16],
  ['oddDelay', 'oddDelay', 'delays.microLabel', 'delays.microHelp', 0, 10000],
  ['stepDelay', 'stepDelay', 'delays.stepLabel', 'delays.stepHelp', 5, 10000],
];
const INITIAL_COLORS = {
  signal_line: { color: '#ff0000', brightness: 1 },
  display: { color: '#00ff00', brightness: 1 },
  bus: { color: '#0000ff', brightness: 1 },
};

function Switch({ label, checked, onChange }: SwitchProps) {
  return (
    <label className="switch" onClick={(event) => event.stopPropagation()} onKeyDown={(event) => event.stopPropagation()}>
      <input type="checkbox" aria-label={label} checked={!!checked} onChange={(event) => onChange?.(event.target.checked)} />
      <span className="slider round" />
    </label>
  );
}

export default function SettingsPanel(props: SettingsPanelProps) {
  const { t } = useI18n();
  const {
    isAnimated = false,
    isMobile,
    lightMode,
    language = 'pl',
    numberFormat,
    decSigned = false,
    codeBits,
    addresBits,
    extras,
    platform = '',
    autocompleteEnabled = true,
    autoResetOnAsmCompile = true,
    creators = [],
    caregivers = [],
    onClose,
    onUpdateExtras,
    onColorChange,
  } = props;
  const [openMap, setOpenMap] = useState<Record<string, boolean>>({});
  const [colors, setColors] = useState<Record<ColorTarget, SavedColor>>(INITIAL_COLORS);
  const [pendingColors, setPendingColors] = useState<Partial<Record<ColorTarget, PendingColor>>>({});
  const [currentColorType, setCurrentColorType] = useState<ColorTarget | null>(null);
  const toggleOpen = (key: string) => setOpenMap((previous) => ({ ...previous, [key]: !previous[key] }));
  const options = <const T extends ToggleValue>(prefix: string, values: readonly (readonly [string, T])[]) =>
    values.map(([key, value]) => ({ label: t(`${prefix}.${key}`), value }));
  const choice = <T extends ToggleValue>(label: ReactNode, values: ToggleOption<T>[], value: T | undefined, onChange?: Update<T>) => (
    <div className="flexColumn">
      {label && <label>{label}:</label>}
      <SegmentedToggle options={values} modelValue={value} onUpdateModelValue={onChange} />
    </div>
  );
  const colorTitles = { signal_line: 'signalLine', display: 'display', bus: 'bus' };
  const applyColor = (colorInfo: ColorSelection) => {
    if (!currentColorType) return;
    setColors((previous) => ({ ...previous, [currentColorType]: colorInfo }));
    setPendingColors((previous) => ({ ...previous, [currentColorType]: { ...colorInfo, type: `${currentColorType}_hex` } }));
    setCurrentColorType(null);
  };
  const sendColors = () => {
    Object.values(pendingColors).forEach(({ type, brightness, colorData }) =>
      onColorChange?.({ type, hex: colorData.hex, rgb: colorData.rgb, hsv: colorData.hsv, brightness, rgbScaled: colorData.rgbScaled })
    );
    setPendingColors({});
  };
  return (
    <div
      id="settings"
      data-component="SettingsPanel"
      className={isAnimated ? 'slide-in' : 'slide-out'}
      onClick={(event) => event.stopPropagation()}
    >
      <header className="settingsHeader">
        <h1>{t('settings.title')}</h1>
        <div className="headerBtns">
          <button className="closeBtn" onClick={onClose} aria-label={t('settings.actions.close')}>
            &times;
          </button>
        </div>
      </header>
      <div className="settingsContent">
        {choice(
          null,
          options('settings.theme', [
            ['light', true],
            ['dark', false],
          ]),
          lightMode,
          props.onUpdateLightMode
        )}
        {choice(
          t('settings.language.label'),
          options('settings.language', [
            ['pl', 'pl'],
            ['en', 'en'],
          ]),
          language,
          props.onUpdateLanguage
        )}
        {choice(
          t('settings.numberFormat.label'),
          options('settings.numberFormat.options', [
            ['dec', 'dec'],
            ['hex', 'hex'],
            ['bin', 'bin'],
          ]),
          numberFormat,
          props.onUpdateNumberFormat
        )}
        {numberFormat === 'dec' && (
          <div className="flexColumn">
            <label>{t('settings.decSigned.label')}:</label>
            <SegmentedToggle
              options={options('settings.decSigned.options', [
                ['unsigned', false],
                ['signed', true],
              ])}
              modelValue={decSigned}
              onUpdateModelValue={props.onUpdateDecSigned}
            />
            <p>{t('settings.decSigned.hint', { bits: codeBits + addresBits })}</p>
          </div>
        )}
        {NUMBERS.map(([key, id, label, help, min, limit]) => {
          const max = key === 'codeBits' ? Math.min(limit, 30 - addresBits) : key === 'addresBits' ? Math.min(limit, 30 - codeBits) : limit;
          return (
            <div key={key} className="flexColumn">
              <label htmlFor={id}>{t(`settings.${label}`)}</label>
              <input
                id={id}
                type="number"
                inputMode="numeric"
                pattern="[0-9]*"
                value={props[key]}
                min={min}
                max={max}
                onChange={(event) => {
                  const value = Number.parseInt(event.target.value, 10);
                  if (Number.isFinite(value) && value >= min && value <= max) {
                    const handler = {
                      codeBits: props.onUpdateCodeBits,
                      addresBits: props.onUpdateAddresBits,
                      oddDelay: props.onUpdateOddDelay,
                      stepDelay: props.onUpdateStepDelay,
                    }[key];
                    handler?.(value);
                  }
                }}
              />
              <p>{t(`settings.${help}`)}</p>
            </div>
          );
        })}
        {platform !== 'esp' && (
          <div className="extras">
            <label>{t('settings.extras.heading')}</label>
            {BOOLEAN_KEYS.map((key) => (
              <div key={key} className="module-toggle-wrapper">
                <span className="module-label">{t(`settings.extras.labels.${key}`)}</span>
                <Switch
                  label={t(`settings.extras.labels.${key}`)}
                  checked={extras[key]}
                  onChange={(checked) => onUpdateExtras?.({ [key]: checked })}
                />
              </div>
            ))}
            {Object.entries(GROUPS).map(([key, children]) => (
              <div key={key} className={`settingsGroup${openMap[key] ? ' open' : ''}`}>
                <div
                  className="settingsGroupHeader"
                  role="button"
                  aria-expanded={!!openMap[key]}
                  tabIndex={0}
                  onClick={() => toggleOpen(key)}
                  onKeyDown={(event) => {
                    if (event.key === 'Enter' || event.key === ' ') {
                      event.preventDefault();
                      toggleOpen(key);
                    }
                  }}
                >
                  <span className="chevron" aria-hidden="true" />
                  <span className="group-title">{t(`settings.extras.groups.${key}.title`)}</span>
                  <Switch
                    label={t(`settings.extras.groups.${key}.title`)}
                    checked={children.every((child) => !!Reflect.get(Reflect.get(extras, key), child) as boolean)}
                    onChange={(checked) => onUpdateExtras?.({ [key]: Object.fromEntries(children.map((child) => [child, checked])) })}
                  />
                </div>
                <div className="collapsible" hidden={!openMap[key]}>
                  {children.map((child) => (
                    <div key={child} className="module-toggle-wrapper">
                      <span className="module-label">{t(`settings.extras.groups.${key}.${child}`)}</span>
                      <Switch
                        label={t(`settings.extras.groups.${key}.${child}`)}
                        checked={Reflect.get(Reflect.get(extras, key), child) as boolean}
                        onChange={(checked) => onUpdateExtras?.({ [key]: { [child]: checked } })}
                      />
                    </div>
                  ))}
                </div>
              </div>
            ))}
          </div>
        )}
        <div className="flexColumn">
          <label>{t('settings.editor.heading')}</label>
          <div className="module-toggle-wrapper">
            <span className="module-label">{t('settings.editor.autocomplete')}</span>
            <Switch label={t('settings.editor.autocomplete')} checked={autocompleteEnabled} onChange={props.onUpdateAutocompleteEnabled} />
          </div>
        </div>
        <div className="flexColumn">
          <label>{t('settings.asm.heading')}</label>
          <div className="module-toggle-wrapper">
            <span className="module-label">{t('settings.asm.reset')}</span>
            <Switch label={t('settings.asm.reset')} checked={autoResetOnAsmCompile} onChange={props.onUpdateAutoResetOnAsmCompile} />
          </div>
          <p>{t('settings.asm.help')}</p>
        </div>
        <div className="flexColumn">
          <div className="flexColumn button-column">
            {(
              [
                ['openLabDialog', 'labs.chooseButton', props.onOpenLabDialog, CommandListIcon],
                ['resetValues', 'settings.actions.resetRegisters', props.onResetValues, RefreshIcon],
                ['defaultSettings', 'settings.actions.defaultSettings', props.onDefaultSettings, RefreshIcon],
                ['openCommandList', 'settings.actions.commandList', props.onOpenCommandList, CommandListIcon],
              ] as const
            ).map(([id, label, handler, Icon]) => (
              <button key={id} id={id} className="SvgAndTextButton compact-button execution-btn execution-btn--step" onClick={handler}>
                <Icon />
                <span>{t(label)}</span>
              </button>
            ))}
          </div>
        </div>
        {platform === 'esp' && (
          <div className="color-section">
            <h3 className="color-section-title">{t('settings.colors.heading')}</h3>
            <div className="color-buttons-list">
              {(Object.keys(colors) as ColorTarget[]).map((key) => (
                <button key={key} className="color-selection-btn" onClick={() => setCurrentColorType(key)}>
                  <span className="color-label">{t(`settings.colors.${key === 'signal_line' ? 'signalLines' : key}`)}</span>
                  <span className="color-dot" style={{ backgroundColor: colors[key].color }} />
                </button>
              ))}
            </div>
            <button className="send-colors-btn" onClick={sendColors} disabled={!Object.keys(pendingColors).length}>
              <span>{t('settings.actions.sendAllColors')}</span>
            </button>
          </div>
        )}
        {currentColorType && (
          <ColorPickerPopup
            visible
            title={t(`settings.colorPicker.${colorTitles[currentColorType]}`)}
            {...colors[currentColorType]}
            onClose={() => setCurrentColorType(null)}
            onApply={applyColor}
          />
        )}
        <PeopleSection isMobile={isMobile} title={t('settings.people.caregivers')} people={caregivers} showGithub={false} />
        <PeopleSection isMobile={isMobile} title={t('settings.people.creators')} people={creators} />
      </div>
    </div>
  );
}

// src/components/Settings/SettingsPanel.vue
<template>
  <div id="settings" :class="{ 'slide-in': isAnimated, 'slide-out': !isAnimated }" @click.stop>
    <header class="settingsHeader">
      <h1>{{ $t('settings.title') }}</h1>
      <div class="headerBtns">
        <button class="closeBtn" @click="$emit('close')" :aria-label="$t('settings.actions.close')">&times;</button>
      </div>
    </header>

    <div class="settingsContent">
      <div class="flexColumn">
        <SegmentedToggle :options="themeOptions" :model-value="lightMode" @update:model-value="$emit('update:lightMode', $event)" />
      </div>

      <div class="flexColumn">
        <label>{{ $t('settings.language.label') }}:</label>
        <SegmentedToggle :options="languageOptions" :model-value="language" @update:model-value="$emit('update:language', $event)" />
      </div>

      <div class="flexColumn">
        <label>{{ $t('settings.numberFormat.label') }}:</label>
        <SegmentedToggle
          :options="numberFormatOptions"
          :model-value="numberFormat"
          @update:model-value="$emit('update:numberFormat', $event)"
          :class="{ active: lightMode }"
        />
      </div>
      <div class="flexColumn" v-if="numberFormat === 'dec'">
        <label>{{ $t('settings.decSigned.label') }}:</label>
        <SegmentedToggle :options="decDisplayOptions" :model-value="decSigned" @update:model-value="$emit('update:decSigned', $event)" />
        <p>{{ $t('settings.decSigned.hint', { bits: codeBits + addresBits }) }}</p>
      </div>

      <div class="flexColumn">
        <label for="commandBits">{{ $t('settings.bits.codeLabel') }}</label>
        <input
          id="commandBits"
          type="number"
          inputmode="numeric"
          pattern="[0-9]*"
          :value="codeBits"
          min="1"
          max="16"
          @input="updateNumber('codeBits', $event.target.value)"
        />
        <p>{{ $t('settings.bits.codeHelp') }}</p>
      </div>

      <div class="flexColumn">
        <label for="addresBits">{{ $t('settings.bits.addressLabel') }}</label>
        <input
          id="addresBits"
          type="number"
          inputmode="numeric"
          pattern="[0-9]*"
          :value="addresBits"
          min="1"
          max="32"
          @input="updateNumber('addresBits', $event.target.value)"
        />
        <p>{{ $t('settings.bits.addressHelp') }}</p>
      </div>

      <div class="flexColumn">
        <label for="oddDelay">{{ $t('settings.delays.microLabel') }}</label>
        <input
          id="oddDelay"
          type="number"
          inputmode="numeric"
          pattern="[0-9]*"
          :value="oddDelay"
          min="0"
          max="10000"
          @input="updateNumber('oddDelay', $event.target.value)"
        />
        <p>{{ $t('settings.delays.microHelp') }}</p>
      </div>

      <div class="flexColumn">
        <label for="stepDelay">{{ $t('settings.delays.stepLabel') }}</label>
        <input
          id="stepDelay"
          type="number"
          inputmode="numeric"
          pattern="[0-9]*"
          :value="stepDelay"
          min="5"
          max="10000"
          @input="updateNumber('stepDelay', $event.target.value)"
        />
        <p>{{ $t('settings.delays.stepHelp') }}</p>
      </div>

      <div class="extras" v-if="platform !== 'esp'">
        <label>{{ $t('settings.extras.heading') }}</label>

        <!-- PROSTE BOOLEANY -->
        <template v-for="key in booleanKeys" :key="key">
          <div class="module-toggle-wrapper">
            <span class="module-label">{{ extrasLabels[key] }}</span>
            <label class="switch">
              <input type="checkbox" :checked="extras[key]" @change="$emit('update:extras', { [key]: $event.target.checked })" />
              <span class="slider round"></span>
            </label>
          </div>
        </template>

        <!-- GRUPY Z DZIEĆMI -->
        <div v-for="group in groupDefs" :key="group.key" class="settingsGroup" :class="{ open: isOpen(group.key) }">
          <!-- Nagłówek: rola przycisku + klawiatura -->
          <div
            class="settingsGroupHeader"
            role="button"
            :aria-expanded="isOpen(group.key)"
            tabindex="0"
            @click="toggleOpen(group.key)"
            @keydown.enter.prevent="toggleOpen(group.key)"
            @keydown.space.prevent="toggleOpen(group.key)"
          >
            <span class="chevron" aria-hidden="true"></span>
            <span class="group-title">{{ group.label }}</span>

            <!-- MASTER SWITCH -->
            <label class="switch" @click.stop>
              <input type="checkbox" :checked="isGroupAllOn(group)" @change="toggleGroup(group, $event.target.checked)" />
              <span class="slider round"></span>
            </label>
          </div>

          <!-- Płynna animacja wysokości -->
          <transition name="collapse" @enter="onEnter" @after-enter="onAfterEnter" @leave="onLeave" @after-leave="onAfterLeave">
            <div v-show="isOpen(group.key)" class="collapsible">
              <div v-for="child in group.children" :key="child.key" class="module-toggle-wrapper">
                <span class="module-label">{{ child.label }}</span>
                <label class="switch">
                  <input
                    type="checkbox"
                    :checked="extras?.[group.key]?.[child.key]"
                    @change="$emit('update:extras', { [group.key]: { [child.key]: $event.target.checked } })"
                  />
                  <span class="slider round"></span>
                </label>
              </div>
            </div>
          </transition>
        </div>
      </div>

      <div class="flexColumn">
        <label>{{ $t('settings.editor.heading') }}</label>
        <div class="module-toggle-wrapper">
          <span class="module-label">{{ $t('settings.editor.autocomplete') }}</span>
          <label class="switch">
            <input type="checkbox" :checked="autocompleteEnabled" @change="$emit('update:autocompleteEnabled', $event.target.checked)" />
            <span class="slider round"></span>
          </label>
        </div>
      </div>
      <div class="flexColumn">
        <label>{{ $t('settings.asm.heading') }}</label>
        <div class="module-toggle-wrapper">
          <span class="module-label">{{ $t('settings.asm.reset') }}</span>
          <label class="switch">
            <input
              type="checkbox"
              :checked="autoResetOnAsmCompile"
              @change="$emit('update:autoResetOnAsmCompile', $event.target.checked)"
            />
            <span class="slider round"></span>
          </label>
        </div>
        <p>{{ $t('settings.asm.help') }}</p>
      </div>

      <div class="flexColumn">
        <div class="flexColumn button-column">
          <button class="SvgAndTextButton compact-button execution-btn execution-btn--step" id="openLabDialog" @click="$emit('open-lab-dialog')">
            <CommandListIcon />
            <span>{{ $t('labs.chooseButton') }}</span>
          </button>
          <button class="SvgAndTextButton compact-button execution-btn execution-btn--step" id="resetValues" @click="$emit('resetValues')">
            <RefreshIcon />
            <span>{{ $t('settings.actions.resetRegisters') }}</span>
          </button>
          <button
            class="SvgAndTextButton compact-button execution-btn execution-btn--step"
            id="defaultSettings"
            @click="$emit('defaultSettings')"
          >
            <RefreshIcon />
            <span>{{ $t('settings.actions.defaultSettings') }}</span>
          </button>
          <button
            class="SvgAndTextButton compact-button execution-btn execution-btn--step"
            id="openCommandList"
            @click="$emit('open-command-list')"
          >
            <CommandListIcon />
            <span>{{ $t('settings.actions.commandList') }}</span>
          </button>
        </div>
      </div>

      <!-- Sekcja kolorów dla ESP32 -->
      <div v-if="platform == 'esp'" class="color-section">
        <h3 class="color-section-title">{{ $t('settings.colors.heading') }}</h3>

        <div class="color-buttons-list">
          <button class="color-selection-btn" @click="openColorPicker('signal_line')">
            <span class="color-label">{{ $t('settings.colors.signalLines') }}</span>
            <div class="color-dot" :style="{ backgroundColor: signalLineColor }"></div>
          </button>

          <button class="color-selection-btn" @click="openColorPicker('display')">
            <span class="color-label">{{ $t('settings.colors.display') }}</span>
            <div class="color-dot" :style="{ backgroundColor: displayColor }"></div>
          </button>

          <button class="color-selection-btn" @click="openColorPicker('bus')">
            <span class="color-label">{{ $t('settings.colors.bus') }}</span>
            <div class="color-dot" :style="{ backgroundColor: busColor }"></div>
          </button>
        </div>

        <button class="send-colors-btn" @click="sendAllColors" :disabled="!hasColorChanges">
          <span>{{ $t('settings.actions.sendAllColors') }}</span>
        </button>
      </div>

      <!-- Popup wyboru koloru -->
      <ColorPickerPopup
        :visible="colorPickerOpen"
        :title="currentColorTitle"
        :color="currentColor"
        :brightness="currentBrightness"
        @close="closeColorPicker"
        @apply="applyColor"
      />

      <PeopleSection :isMobile="isMobile" :title="$t('settings.people.caregivers')" :people="caregivers" :showGithub="false" :columns="2" />
      <PeopleSection :isMobile="isMobile" :title="$t('settings.people.creators')" :people="creators" :showGithub="true" :columns="2" />
    </div>
  </div>
</template>

<script>
import SunIcon from '@/assets/svg/SunIcon.vue';
import MoonIcon from '@/assets/svg/MoonIcon.vue';
import RefreshIcon from '@/assets/svg/RefreshIcon.vue';
import CommandListIcon from '@/assets/svg/CommandListIcon.vue';
import SegmentedToggle from '@/components/SegmentedToggle.vue';
import PeopleSection from './PeopleSection.vue';
import ColorPickerPopup from './ColorPickerPopup.vue';

export default {
  name: 'SettingsPanel',
  components: { SunIcon, MoonIcon, RefreshIcon, CommandListIcon, SegmentedToggle, PeopleSection, ColorPickerPopup },
  props: {
    isAnimated: { type: Boolean, default: false },
    lightMode: { type: Boolean, required: true },
    isMobile: { type: Boolean, required: true },
    numberFormat: { type: String, required: true },
    creators: { type: Array, default: () => [] },
    caregivers: { type: Array, default: () => [] },
    language: { type: String, default: 'pl' },
    codeBits: { type: Number, required: true },
    addresBits: { type: Number, required: true },
    oddDelay: { type: Number, required: true },
    stepDelay: { type: Number, required: true },
    extras: { type: Object, required: true },
    platform: { type: String, default: '' },
    autocompleteEnabled: { type: Boolean, default: true },
    decSigned: { type: Boolean, default: false },
    autoResetOnAsmCompile: { type: Boolean, default: true },
  },
  data() {
    return {
      signalLineColor: '#ff0000',
      signalLineBrightness: 1,
      displayColor: '#00ff00',
      displayBrightness: 1,
      busColor: '#0000ff',
      busBrightness: 1,

      colorPickerOpen: false,
      currentColorType: null,
      currentColorTitle: '',
      currentColor: '#ff0000',
      currentBrightness: 1,

      pendingColors: {},
      hasColorChanges: false,

      openMap: {},
    };
  },
  emits: [
    'close',
    'update:lightMode',
    'update:numberFormat',
    'update:codeBits',
    'update:addresBits',
    'update:oddDelay',
    'update:stepDelay',
    'update:extras',
    'resetValues',
    'defaultSettings',
    'open-command-list',
    'open-lab-dialog',
    'update:autocompleteEnabled',
    'update:decSigned',
    'update:autoResetOnAsmCompile',
    'color-change',
    'update:language',
  ],
  computed: {
    themeOptions() {
      return [
        { label: this.$t('settings.theme.light'), value: true },
        { label: this.$t('settings.theme.dark'), value: false },
      ];
    },
    languageOptions() {
      return [
        { label: this.$t('settings.language.pl'), value: 'pl' },
        { label: this.$t('settings.language.en'), value: 'en' },
      ];
    },
    numberFormatOptions() {
      return [
        { label: this.$t('settings.numberFormat.options.dec'), value: 'dec' },
        { label: this.$t('settings.numberFormat.options.hex'), value: 'hex' },
        { label: this.$t('settings.numberFormat.options.bin'), value: 'bin' },
      ];
    },
    decDisplayOptions() {
      return [
        { label: this.$t('settings.decSigned.options.unsigned'), value: false },
        { label: this.$t('settings.decSigned.options.signed'), value: true },
      ];
    },
    extrasLabels() {
      return {
        xRegister: this.$t('settings.extras.labels.xRegister'),
        yRegister: this.$t('settings.extras.labels.yRegister'),
        dl: this.$t('settings.extras.labels.dl'),
        jamlExtras: this.$t('settings.extras.labels.jamlExtras'),
        busConnectors: this.$t('settings.extras.labels.busConnectors'),
        showInvisibleRegisters: this.$t('settings.extras.labels.showInvisibleRegisters'),
      };
    },
    booleanKeys() {
      return ['xRegister', 'yRegister', 'dl', 'jamlExtras', 'busConnectors', 'showInvisibleRegisters'];
    },
    groupDefs() {
      return [
        {
          key: 'io',
          label: this.$t('settings.extras.groups.io.title'),
          children: [
            { key: 'rbRegister', label: this.$t('settings.extras.groups.io.rbRegister') },
            { key: 'gRegister', label: this.$t('settings.extras.groups.io.gRegister') },
          ],
        },
        {
          key: 'stack',
          label: this.$t('settings.extras.groups.stack.title'),
          children: [
            { key: 'wsRegister', label: this.$t('settings.extras.groups.stack.wsRegister') },
            { key: 'wylsSignal', label: this.$t('settings.extras.groups.stack.wylsSignal') },
          ],
        },
        {
          key: 'interrupts',
          label: this.$t('settings.extras.groups.interrupts.title'),
          children: [
            { key: 'rzRegister', label: this.$t('settings.extras.groups.interrupts.rzRegister') },
            { key: 'rpRegister', label: this.$t('settings.extras.groups.interrupts.rpRegister') },
            { key: 'rmRegister', label: this.$t('settings.extras.groups.interrupts.rmRegister') },
            { key: 'apRegister', label: this.$t('settings.extras.groups.interrupts.apRegister') },
            { key: 'rintSignal', label: this.$t('settings.extras.groups.interrupts.rintSignal') },
            { key: 'eniSignal', label: this.$t('settings.extras.groups.interrupts.eniSignal') },
          ],
        },
      ];
    },
  },
  methods: {
    openColorPicker(type) {
      this.currentColorType = type;

      const colorMap = {
        signal_line: {
          title: this.$t('settings.colorPicker.signalLine'),
          color: this.signalLineColor,
          brightness: this.signalLineBrightness,
        },
        display: {
          title: this.$t('settings.colorPicker.display'),
          color: this.displayColor,
          brightness: this.displayBrightness,
        },
        bus: {
          title: this.$t('settings.colorPicker.bus'),
          color: this.busColor,
          brightness: this.busBrightness,
        },
      };

      const config = colorMap[type];
      this.currentColorTitle = config.title;
      this.currentColor = config.color;
      this.currentBrightness = config.brightness;
      this.colorPickerOpen = true;
    },

    closeColorPicker() {
      this.colorPickerOpen = false;
      this.currentColorType = null;
    },

    applyColor({ color, brightness, colorData }) {
      if (this.currentColorType === 'signal_line') {
        this.signalLineColor = color;
        this.signalLineBrightness = brightness;
      } else if (this.currentColorType === 'display') {
        this.displayColor = color;
        this.displayBrightness = brightness;
      } else if (this.currentColorType === 'bus') {
        this.busColor = color;
        this.busBrightness = brightness;
      }

      this.pendingColors[this.currentColorType] = {
        type: this.currentColorType + '_hex',
        color,
        brightness,
        colorData,
      };

      this.hasColorChanges = Object.keys(this.pendingColors).length > 0;
      this.closeColorPicker();
    },

    sendAllColors() {
      Object.values(this.pendingColors).forEach((colorInfo) => {
        this.$emit('color-change', {
          type: colorInfo.type,
          hex: colorInfo.colorData.hex,
          rgb: colorInfo.colorData.rgb,
          hsv: colorInfo.colorData.hsv,
          brightness: colorInfo.brightness,
          rgbScaled: colorInfo.colorData.rgbScaled,
        });
      });

      this.pendingColors = {};
      this.hasColorChanges = false;
    },
    updateNumber(key, value) {
      const n = parseInt(value, 10);
      if (Number.isNaN(n)) return;
      const rules = {
        codeBits: { min: 1, max: 16 },
        addresBits: { min: 1, max: 32 },
        oddDelay: { min: 0, max: 10000 },
        stepDelay: { min: 5, max: 10000 },
      }[key];
      if (!rules) {
        if (n >= 0) this.$emit(`update:${key}`, n);
        return;
      }
      if (n >= rules.min && n <= rules.max) this.$emit(`update:${key}`, n);
    },

    isGroupAllOn(group) {
      const obj = this.extras?.[group.key] || {};
      return group.children.every((ch) => !!obj[ch.key]);
    },
    toggleGroup(group, checked) {
      const patch = {};
      for (const ch of group.children) patch[ch.key] = !!checked;
      this.$emit('update:extras', { [group.key]: patch });
    },

    isOpen(key) {
      return !!this.openMap[key];
    },
    toggleOpen(key) {
      this.openMap = { ...this.openMap, [key]: !this.openMap[key] };
    },

    onEnter(el) {
      el.style.height = '0px';
      el.style.overflow = 'hidden';
      void el.offsetHeight;
      el.style.height = el.scrollHeight + 'px';
    },
    onAfterEnter(el) {
      el.style.height = 'auto';
      el.style.overflow = '';
    },
    onLeave(el) {
      el.style.height = el.scrollHeight + 'px';
      el.style.overflow = 'hidden';
      void el.offsetHeight;
      el.style.height = '0px';
    },
    onAfterLeave(el) {
      el.style.overflow = '';
    },
  },
};
</script>

<style scoped>
#settings {
  position: fixed;
  top: 0;
  right: 0;
  height: 100vh;
  width: 400px;
  max-width: 90vw;
  z-index: 101;
  background-color: var(--panelBackgroundColor);
  border-left: 1px solid var(--panelOutlineColor);
  box-shadow: -4px 0 20px rgba(0, 0, 0, 0.3);
  display: flex;
  flex-direction: column;
  transform: translateX(100%);
  transition: transform 0.3s cubic-bezier(0.25, 0.46, 0.45, 0.94);
}

#settings.slide-in {
  transform: translateX(0);
}

#settings.slide-out {
  transform: translateX(100%);
}

.settingsContent {
  flex: 1;
  overflow-y: auto;
  padding: 1rem;
  display: flex;
  flex-direction: column;
  gap: 1.5rem;
}

.settingsHeader {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 0.75rem 1rem;
  background: #003c7d;
  color: #fff;
}

.settingsGroup {
  text-align: start;
}

.settingsGroup.open .chevron {
  transform: rotate(90deg);
}

.settingsGroupHeader {
  display: grid;
  grid-template-columns: auto 1fr auto;
  align-items: center;
  gap: 0.5rem;
  padding: 8px 0;
  cursor: pointer;
  user-select: none;
}

.settingsGroupHeader .chevron {
  width: 0;
  height: 0;
  border-left: 6px solid var(--fontColor);
  border-top: 4px solid transparent;
  border-bottom: 4px solid transparent;
  transition: transform 0.22s ease;
  margin-right: 2px;
}

.settingsGroupHeader .group-title {
  color: var(--fontColor);
  font-weight: 600;
}

.collapse-enter-active,
.collapse-leave-active {
  transition: height 0.25s ease;
}

.collapsible {
  overflow: hidden;
}

.settingsHeader h1 {
  font-size: 1.25rem;
  color: #fff;
  margin: 0;
}

.switch {
  position: relative;
  display: inline-block;
  width: 70px;
  height: 34px;
}

.switch input {
  opacity: 0;
  width: 0;
  height: 0;
}

.slider {
  position: absolute;
  cursor: pointer;
  inset: 0;
  background: var(--backgroundColorItem);
  transition: 0.4s;
}

.slider:before {
  content: '';
  position: absolute;
  height: 26px;
  width: 26px;
  left: 4px;
  bottom: 4px;
  background: var(--backgroundColorPartOfItem);
  transition: 0.4s;
}

input:checked + .slider {
  background: #003c7d;
}

input:focus + .slider {
  box-shadow: 0 0 1px #003c7d;
}

input:checked + .slider:before {
  transform: translateX(36px);
}

.slider.round {
  border-radius: 0.25rem;
}

.slider.round:before {
  border-radius: 0.25rem;
}

.button-column {
  gap: 0.75rem;
}

.compact-button {
  width: auto !important;
  max-width: 100% !important;
  min-width: 0 !important;
  flex-shrink: 1 !important;
  padding: 0.5rem 1rem !important;
  font-size: 0.85rem !important;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}

.compact-button span {
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}

.module-toggle-wrapper {
  display: flex;
  justify-content: space-between;
  align-items: center;
  gap: 1rem;
  padding: 0.5rem 0;
}

.module-label {
  color: var(--fontColor);
}

.number-format-toggle {
  width: 100%;
}

.multiToggleButton {
  display: flex;
  border-radius: var(--default-border-radius);
  overflow: hidden;
  border: 1px solid var(--panelOutlineColor);
}

.multiToggleButton span {
  flex: 1;
  padding: 0.75rem;
  display: flex;
  align-items: center;
  justify-content: center;
  cursor: pointer;
  background: var(--buttonBackgroundColor);
  color: var(--buttonTextColor);
  transition: 0.2s;
  font-size: 0.9rem;
}

.multiToggleButton span:hover {
  background: var(--buttonHoverColor);
}

.format-toggle {
  display: grid;
  grid-template-columns: 1fr 1fr 1fr;
  min-width: 180px;
}

.format-toggle span {
  background: var(--buttonBackgroundColor);
  color: var(--buttonTextColor, black);
}

.format-toggle.active-dec span:nth-child(1),
.format-toggle.active-hex span:nth-child(2),
.format-toggle.active-bin span:nth-child(3) {
  background: var(--signal-active);
  color: #fff;
}

.format-toggle.active-dec span:nth-child(1):hover,
.format-toggle.active-hex span:nth-child(2):hover,
.format-toggle.active-bin span:nth-child(3):hover {
  background: var(--signal-active);
}

.toggleButtonDiv {
  display: flex;
  border-radius: var(--default-border-radius);
  overflow: hidden;
  border: 1px solid var(--panelOutlineColor);
}

.toggleButtonDiv span {
  flex: 1;
  padding: 0.75rem;
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 0.5rem;
  cursor: pointer;
  background: var(--buttonBackgroundColor);
  color: var(--buttonTextColor);
  transition: 0.2s;
  font-size: 0.9rem;
}

.toggleButtonDiv span:hover {
  background: var(--buttonHoverColor);
}

.toggleButtonDiv.active span:first-child {
  background: var(--signal-active);
  color: #fff;
}

.toggleButtonDiv:not(.active) span:last-child {
  background: var(--signal-active);
  color: #fff;
}

.SvgAndTextButton {
  display: flex;
  align-items: center;
  gap: 0.5rem;
  padding: 0.75rem 1rem;
  border: 1px solid var(--panelOutlineColor);
  border-radius: var(--default-border-radius);
  background: var(--buttonBackgroundColor);
  color: var(--buttonTextColor);
  cursor: pointer;
  transition: 0.2s;
  font-size: 0.9rem;
  flex: 1;
  justify-content: center;
}

.SvgAndTextButton:hover {
  background: var(--buttonHoverColor);
  transform: translateY(-1px);
}

.SvgAndTextButton:active {
  background: var(--buttonActiveColor);
  transform: translateY(0);
}

#settings .flexColumn {
  display: flex;
  flex-direction: column;
  gap: 0.5rem;
  margin-bottom: 20px;
}

#settings input[type='number'] {
  padding: 0.5rem;
  border-radius: var(--default-border-radius);
  border: 1px solid var(--panelOutlineColor);
  background: var(--backgroundColor);
  color: var(--fontColor);
  font-size: 0.9rem;
  transition: border-color 0.2s;
}

#settings input[type='number']:focus {
  border-color: var(--signal-active);
  outline: none;
}

#settings label {
  font-weight: 500;
  color: var(--fontColor);
  margin-bottom: 0.25rem;
  text-align: left !important;
}

#settings p {
  font-size: 0.85rem;
  color: var(--fontColor);
  opacity: 0.7;
  margin: 0.25rem 0 0 0;
  line-height: 1.4;
}

/* Sekcja kolorów */
.color-section {
  margin: 20px 0;
  padding: 20px 0;
  border-top: 1px solid var(--panelOutlineColor);
}

.color-section-title {
  color: var(--fontColor);
  font-size: 1.1rem;
  font-weight: 600;
  margin: 0 0 20px 0;
  text-align: center;
}

.color-buttons-list {
  display: flex;
  flex-direction: column;
  gap: 8px;
  margin-bottom: 20px;
}

.color-selection-btn {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 12px 16px;
  border: 1px solid var(--panelOutlineColor);
  border-radius: var(--default-border-radius);
  background: var(--buttonBackgroundColor);
  color: var(--buttonTextColor);
  cursor: pointer;
  transition: all 0.2s ease;
}

.color-selection-btn:hover {
  background: var(--buttonHoverColor);
  border-color: #003c7d;
  transform: translateY(-1px);
  box-shadow: 0 2px 8px rgba(0, 60, 125, 0.15);
}

.color-label {
  font-size: 0.9rem;
  font-weight: 500;
}

.color-dot {
  width: 20px;
  height: 20px;
  border-radius: 50%;
  border: 2px solid var(--panelOutlineColor);
  flex-shrink: 0;
  box-shadow: 0 1px 3px rgba(0, 0, 0, 0.2);
}

.send-colors-btn {
  width: 100%;
  padding: 12px 20px;
  background: #003c7d;
  color: white;
  border: 1px solid #003c7d;
  border-radius: var(--default-border-radius);
  cursor: pointer;
  font-size: 0.95rem;
  font-weight: 500;
  transition: all 0.2s ease;
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 8px;
}

.send-colors-btn:hover:not(:disabled) {
  background: #0056b3;
  border-color: #0056b3;
  transform: translateY(-1px);
  box-shadow: 0 4px 12px rgba(0, 86, 179, 0.3);
}

.send-colors-btn:disabled {
  background: var(--buttonBackgroundColor);
  color: var(--fontColor);
  border-color: var(--panelOutlineColor);
  cursor: not-allowed;
  opacity: 0.5;
}

.color-picker-group {
  margin-bottom: 25px;
  padding: 15px;
  background: var(--panelBackgroundColorSecondary, rgba(0, 0, 0, 0.1));
  border-radius: var(--default-border-radius);
  border: 1px solid var(--panelOutlineColor);
}

.color-picker-label {
  color: var(--fontColor);
  font-size: 0.95rem;
  font-weight: 500;
  margin: 0 0 15px 0;
  text-align: center;
  opacity: 0.9;
}

/* Custom scrollbar styles for settings content */
.settingsContent::-webkit-scrollbar {
  width: 12px;
}

.settingsContent::-webkit-scrollbar-track {
  background: var(--panelBackgroundColor);
  border-radius: 6px;
}

.settingsContent::-webkit-scrollbar-thumb {
  background: #003c7d;
  border-radius: 6px;
  transition: background-color 0.2s;
}

.settingsContent::-webkit-scrollbar-thumb:hover {
  background: #0056b3;
}

.settingsContent::-webkit-scrollbar-thumb:active {
  background: #002a5c;
}

/* Scrollbar corner */
.settingsContent::-webkit-scrollbar-corner {
  background: var(--panelBackgroundColor);
}

/* Scrollbar buttons (arrows) */
.settingsContent::-webkit-scrollbar-button {
  display: block;
  height: 12px;
  width: 12px;
  background: #003c7d;
  border-radius: 0;
}

.settingsContent::-webkit-scrollbar-button:hover {
  background: #0056b3;
}

.settingsContent::-webkit-scrollbar-button:active {
  background: #002a5c;
}

/* Up arrow */
.settingsContent::-webkit-scrollbar-button:vertical:start:decrement {
  background-image: url('data:image/svg+xml,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="white"><path d="M7 14l5-5 5 5z"/></svg>');
  background-repeat: no-repeat;
  background-position: center;
  background-size: 8px;
}

/* Down arrow */
.settingsContent::-webkit-scrollbar-button:vertical:end:increment {
  background-image: url('data:image/svg+xml,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="white"><path d="M7 10l5 5 5-5z"/></svg>');
  background-repeat: no-repeat;
  background-position: center;
  background-size: 8px;
}

/* Firefox scrollbar */
.settingsContent {
  scrollbar-width: auto;
  scrollbar-color: #003c7d var(--panelBackgroundColor);
}
</style>
